// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package appregister

import (
	"context"
	"glintfed/ent"
	"glintfed/internal/model"
	"sync"
)

// Ensure, that UserModelMock does implement UserModel.
// If this is not the case, regenerate this file with moq.
var _ UserModel = &UserModelMock{}

// UserModelMock is a mock implementation of UserModel.
//
//	func TestSomethingThatUsesUserModel(t *testing.T) {
//
//		// make and configure a mocked UserModel
//		mockedUserModel := &UserModelMock{
//			CreateFunc: func(ctx context.Context, params model.CreateUserParams) (*ent.User, error) {
//				panic("mock out the Create method")
//			},
//		}
//
//		// use mockedUserModel in code that requires UserModel
//		// and then make assertions.
//
//	}
type UserModelMock struct {
	// CreateFunc mocks the Create method.
	CreateFunc func(ctx context.Context, params model.CreateUserParams) (*ent.User, error)

	// calls tracks calls to the methods.
	calls struct {
		// Create holds details about calls to the Create method.
		Create []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params model.CreateUserParams
		}
	}
	lockCreate sync.RWMutex
}

// Create calls CreateFunc.
func (mock *UserModelMock) Create(ctx context.Context, params model.CreateUserParams) (*ent.User, error) {
	if mock.CreateFunc == nil {
		panic("UserModelMock.CreateFunc: method is nil but UserModel.Create was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params model.CreateUserParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockCreate.Lock()
	mock.calls.Create = append(mock.calls.Create, callInfo)
	mock.lockCreate.Unlock()
	return mock.CreateFunc(ctx, params)
}

// CreateCalls gets all the calls that were made to Create.
// Check the length with:
//
//	len(mockedUserModel.CreateCalls())
func (mock *UserModelMock) CreateCalls() []struct {
	Ctx    context.Context
	Params model.CreateUserParams
} {
	var calls []struct {
		Ctx    context.Context
		Params model.CreateUserParams
	}
	mock.lockCreate.RLock()
	calls = mock.calls.Create
	mock.lockCreate.RUnlock()
	return calls
}
