// Code generated by ent, DO NOT EDIT.

package pulseentry

import (
	"glintfed/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLTE(FieldID, id))
}

// Timestamp applies equality check predicate on the "timestamp" field. It's identical to TimestampEQ.
func Timestamp(v uint) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldTimestamp, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldType, v))
}

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldKey, v))
}

// KeyHash applies equality check predicate on the "key_hash" field. It's identical to KeyHashEQ.
func KeyHash(v []byte) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldKeyHash, v))
}

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v int64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldValue, v))
}

// TimestampEQ applies the EQ predicate on the "timestamp" field.
func TimestampEQ(v uint) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldTimestamp, v))
}

// TimestampNEQ applies the NEQ predicate on the "timestamp" field.
func TimestampNEQ(v uint) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNEQ(FieldTimestamp, v))
}

// TimestampIn applies the In predicate on the "timestamp" field.
func TimestampIn(vs ...uint) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldIn(FieldTimestamp, vs...))
}

// TimestampNotIn applies the NotIn predicate on the "timestamp" field.
func TimestampNotIn(vs ...uint) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNotIn(FieldTimestamp, vs...))
}

// TimestampGT applies the GT predicate on the "timestamp" field.
func TimestampGT(v uint) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGT(FieldTimestamp, v))
}

// TimestampGTE applies the GTE predicate on the "timestamp" field.
func TimestampGTE(v uint) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGTE(FieldTimestamp, v))
}

// TimestampLT applies the LT predicate on the "timestamp" field.
func TimestampLT(v uint) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLT(FieldTimestamp, v))
}

// TimestampLTE applies the LTE predicate on the "timestamp" field.
func TimestampLTE(v uint) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLTE(FieldTimestamp, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldContainsFold(FieldType, v))
}

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldKey, v))
}

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNEQ(FieldKey, v))
}

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldIn(FieldKey, vs...))
}

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNotIn(FieldKey, vs...))
}

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGT(FieldKey, v))
}

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGTE(FieldKey, v))
}

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLT(FieldKey, v))
}

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLTE(FieldKey, v))
}

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldContains(FieldKey, v))
}

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldHasPrefix(FieldKey, v))
}

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldHasSuffix(FieldKey, v))
}

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEqualFold(FieldKey, v))
}

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldContainsFold(FieldKey, v))
}

// KeyHashEQ applies the EQ predicate on the "key_hash" field.
func KeyHashEQ(v []byte) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldKeyHash, v))
}

// KeyHashNEQ applies the NEQ predicate on the "key_hash" field.
func KeyHashNEQ(v []byte) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNEQ(FieldKeyHash, v))
}

// KeyHashIn applies the In predicate on the "key_hash" field.
func KeyHashIn(vs ...[]byte) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldIn(FieldKeyHash, vs...))
}

// KeyHashNotIn applies the NotIn predicate on the "key_hash" field.
func KeyHashNotIn(vs ...[]byte) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNotIn(FieldKeyHash, vs...))
}

// KeyHashGT applies the GT predicate on the "key_hash" field.
func KeyHashGT(v []byte) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGT(FieldKeyHash, v))
}

// KeyHashGTE applies the GTE predicate on the "key_hash" field.
func KeyHashGTE(v []byte) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGTE(FieldKeyHash, v))
}

// KeyHashLT applies the LT predicate on the "key_hash" field.
func KeyHashLT(v []byte) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLT(FieldKeyHash, v))
}

// KeyHashLTE applies the LTE predicate on the "key_hash" field.
func KeyHashLTE(v []byte) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLTE(FieldKeyHash, v))
}

// KeyHashIsNil applies the IsNil predicate on the "key_hash" field.
func KeyHashIsNil() predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldIsNull(FieldKeyHash))
}

// KeyHashNotNil applies the NotNil predicate on the "key_hash" field.
func KeyHashNotNil() predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNotNull(FieldKeyHash))
}

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v int64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldEQ(FieldValue, v))
}

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v int64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNEQ(FieldValue, v))
}

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...int64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldIn(FieldValue, vs...))
}

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...int64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNotIn(FieldValue, vs...))
}

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v int64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGT(FieldValue, v))
}

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v int64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldGTE(FieldValue, v))
}

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v int64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLT(FieldValue, v))
}

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v int64) predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldLTE(FieldValue, v))
}

// ValueIsNil applies the IsNil predicate on the "value" field.
func ValueIsNil() predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldIsNull(FieldValue))
}

// ValueNotNil applies the NotNil predicate on the "value" field.
func ValueNotNil() predicate.PulseEntry {
	return predicate.PulseEntry(sql.FieldNotNull(FieldValue))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PulseEntry) predicate.PulseEntry {
	return predicate.PulseEntry(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PulseEntry) predicate.PulseEntry {
	return predicate.PulseEntry(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PulseEntry) predicate.PulseEntry {
	return predicate.PulseEntry(sql.NotPredicates(p))
}
