// Code generated by ent, DO NOT EDIT.

package grouplimit

import (
	"glintfed/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLTE(FieldID, id))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldGroupID, v))
}

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldProfileID, v))
}

// Limits applies equality check predicate on the "limits" field. It's identical to LimitsEQ.
func Limits(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldLimits, v))
}

// Metadata applies equality check predicate on the "metadata" field. It's identical to MetadataEQ.
func Metadata(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldMetadata, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldUpdatedAt, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLTE(FieldGroupID, v))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotIn(FieldProfileID, vs...))
}

// ProfileIDGT applies the GT predicate on the "profile_id" field.
func ProfileIDGT(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGT(FieldProfileID, v))
}

// ProfileIDGTE applies the GTE predicate on the "profile_id" field.
func ProfileIDGTE(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGTE(FieldProfileID, v))
}

// ProfileIDLT applies the LT predicate on the "profile_id" field.
func ProfileIDLT(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLT(FieldProfileID, v))
}

// ProfileIDLTE applies the LTE predicate on the "profile_id" field.
func ProfileIDLTE(v uint64) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLTE(FieldProfileID, v))
}

// LimitsEQ applies the EQ predicate on the "limits" field.
func LimitsEQ(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldLimits, v))
}

// LimitsNEQ applies the NEQ predicate on the "limits" field.
func LimitsNEQ(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNEQ(FieldLimits, v))
}

// LimitsIn applies the In predicate on the "limits" field.
func LimitsIn(vs ...string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIn(FieldLimits, vs...))
}

// LimitsNotIn applies the NotIn predicate on the "limits" field.
func LimitsNotIn(vs ...string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotIn(FieldLimits, vs...))
}

// LimitsGT applies the GT predicate on the "limits" field.
func LimitsGT(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGT(FieldLimits, v))
}

// LimitsGTE applies the GTE predicate on the "limits" field.
func LimitsGTE(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGTE(FieldLimits, v))
}

// LimitsLT applies the LT predicate on the "limits" field.
func LimitsLT(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLT(FieldLimits, v))
}

// LimitsLTE applies the LTE predicate on the "limits" field.
func LimitsLTE(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLTE(FieldLimits, v))
}

// LimitsContains applies the Contains predicate on the "limits" field.
func LimitsContains(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldContains(FieldLimits, v))
}

// LimitsHasPrefix applies the HasPrefix predicate on the "limits" field.
func LimitsHasPrefix(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldHasPrefix(FieldLimits, v))
}

// LimitsHasSuffix applies the HasSuffix predicate on the "limits" field.
func LimitsHasSuffix(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldHasSuffix(FieldLimits, v))
}

// LimitsIsNil applies the IsNil predicate on the "limits" field.
func LimitsIsNil() predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIsNull(FieldLimits))
}

// LimitsNotNil applies the NotNil predicate on the "limits" field.
func LimitsNotNil() predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotNull(FieldLimits))
}

// LimitsEqualFold applies the EqualFold predicate on the "limits" field.
func LimitsEqualFold(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEqualFold(FieldLimits, v))
}

// LimitsContainsFold applies the ContainsFold predicate on the "limits" field.
func LimitsContainsFold(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldContainsFold(FieldLimits, v))
}

// MetadataEQ applies the EQ predicate on the "metadata" field.
func MetadataEQ(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldMetadata, v))
}

// MetadataNEQ applies the NEQ predicate on the "metadata" field.
func MetadataNEQ(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNEQ(FieldMetadata, v))
}

// MetadataIn applies the In predicate on the "metadata" field.
func MetadataIn(vs ...string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIn(FieldMetadata, vs...))
}

// MetadataNotIn applies the NotIn predicate on the "metadata" field.
func MetadataNotIn(vs ...string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotIn(FieldMetadata, vs...))
}

// MetadataGT applies the GT predicate on the "metadata" field.
func MetadataGT(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGT(FieldMetadata, v))
}

// MetadataGTE applies the GTE predicate on the "metadata" field.
func MetadataGTE(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGTE(FieldMetadata, v))
}

// MetadataLT applies the LT predicate on the "metadata" field.
func MetadataLT(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLT(FieldMetadata, v))
}

// MetadataLTE applies the LTE predicate on the "metadata" field.
func MetadataLTE(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLTE(FieldMetadata, v))
}

// MetadataContains applies the Contains predicate on the "metadata" field.
func MetadataContains(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldContains(FieldMetadata, v))
}

// MetadataHasPrefix applies the HasPrefix predicate on the "metadata" field.
func MetadataHasPrefix(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldHasPrefix(FieldMetadata, v))
}

// MetadataHasSuffix applies the HasSuffix predicate on the "metadata" field.
func MetadataHasSuffix(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldHasSuffix(FieldMetadata, v))
}

// MetadataIsNil applies the IsNil predicate on the "metadata" field.
func MetadataIsNil() predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIsNull(FieldMetadata))
}

// MetadataNotNil applies the NotNil predicate on the "metadata" field.
func MetadataNotNil() predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotNull(FieldMetadata))
}

// MetadataEqualFold applies the EqualFold predicate on the "metadata" field.
func MetadataEqualFold(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEqualFold(FieldMetadata, v))
}

// MetadataContainsFold applies the ContainsFold predicate on the "metadata" field.
func MetadataContainsFold(v string) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldContainsFold(FieldMetadata, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.GroupLimit {
	return predicate.GroupLimit(sql.FieldNotNull(FieldUpdatedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.GroupLimit) predicate.GroupLimit {
	return predicate.GroupLimit(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.GroupLimit) predicate.GroupLimit {
	return predicate.GroupLimit(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.GroupLimit) predicate.GroupLimit {
	return predicate.GroupLimit(sql.NotPredicates(p))
}
