// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"glintfed/ent/activity"
	"glintfed/ent/profile"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Activity is the model entity for the Activity schema.
type Activity struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// ToID holds the value of the "to_id" field.
	ToID *uint64 `json:"to_id,omitempty"`
	// FromID holds the value of the "from_id" field.
	FromID *uint64 `json:"from_id,omitempty"`
	// ObjectType holds the value of the "object_type" field.
	ObjectType *string `json:"object_type,omitempty"`
	// Data holds the value of the "data" field.
	Data *string `json:"data,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ActivityQuery when eager-loading is set.
	Edges        ActivityEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ActivityEdges holds the relations/edges for other nodes in the graph.
type ActivityEdges struct {
	// ToProfile holds the value of the toProfile edge.
	ToProfile *Profile `json:"toProfile,omitempty"`
	// FromProfile holds the value of the fromProfile edge.
	FromProfile *Profile `json:"fromProfile,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ToProfileOrErr returns the ToProfile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityEdges) ToProfileOrErr() (*Profile, error) {
	if e.ToProfile != nil {
		return e.ToProfile, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: profile.Label}
	}
	return nil, &NotLoadedError{edge: "toProfile"}
}

// FromProfileOrErr returns the FromProfile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ActivityEdges) FromProfileOrErr() (*Profile, error) {
	if e.FromProfile != nil {
		return e.FromProfile, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: profile.Label}
	}
	return nil, &NotLoadedError{edge: "fromProfile"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Activity) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case activity.FieldID, activity.FieldToID, activity.FieldFromID:
			values[i] = new(sql.NullInt64)
		case activity.FieldObjectType, activity.FieldData:
			values[i] = new(sql.NullString)
		case activity.FieldProcessedAt, activity.FieldCreatedAt, activity.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Activity fields.
func (_m *Activity) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case activity.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case activity.FieldToID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field to_id", values[i])
			} else if value.Valid {
				_m.ToID = new(uint64)
				*_m.ToID = uint64(value.Int64)
			}
		case activity.FieldFromID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field from_id", values[i])
			} else if value.Valid {
				_m.FromID = new(uint64)
				*_m.FromID = uint64(value.Int64)
			}
		case activity.FieldObjectType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_type", values[i])
			} else if value.Valid {
				_m.ObjectType = new(string)
				*_m.ObjectType = value.String
			}
		case activity.FieldData:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field data", values[i])
			} else if value.Valid {
				_m.Data = new(string)
				*_m.Data = value.String
			}
		case activity.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		case activity.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case activity.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Activity.
// This includes values selected through modifiers, order, etc.
func (_m *Activity) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryToProfile queries the "toProfile" edge of the Activity entity.
func (_m *Activity) QueryToProfile() *ProfileQuery {
	return NewActivityClient(_m.config).QueryToProfile(_m)
}

// QueryFromProfile queries the "fromProfile" edge of the Activity entity.
func (_m *Activity) QueryFromProfile() *ProfileQuery {
	return NewActivityClient(_m.config).QueryFromProfile(_m)
}

// Update returns a builder for updating this Activity.
// Note that you need to call Activity.Unwrap() before calling this method if this Activity
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Activity) Update() *ActivityUpdateOne {
	return NewActivityClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Activity entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Activity) Unwrap() *Activity {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Activity is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Activity) String() string {
	var builder strings.Builder
	builder.WriteString("Activity(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.ToID; v != nil {
		builder.WriteString("to_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FromID; v != nil {
		builder.WriteString("from_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ObjectType; v != nil {
		builder.WriteString("object_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Data; v != nil {
		builder.WriteString("data=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Activities is a parsable slice of Activity.
type Activities []*Activity
