// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/avatar"
	"glintfed/ent/predicate"
	"glintfed/ent/profile"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// AvatarUpdate is the builder for updating Avatar entities.
type AvatarUpdate struct {
	config
	hooks    []Hook
	mutation *AvatarMutation
}

// Where appends a list predicates to the AvatarUpdate builder.
func (_u *AvatarUpdate) Where(ps ...predicate.Avatar) *AvatarUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *AvatarUpdate) SetProfileID(v uint64) *AvatarUpdate {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableProfileID(v *uint64) *AvatarUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetMediaPath sets the "media_path" field.
func (_u *AvatarUpdate) SetMediaPath(v string) *AvatarUpdate {
	_u.mutation.SetMediaPath(v)
	return _u
}

// SetNillableMediaPath sets the "media_path" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableMediaPath(v *string) *AvatarUpdate {
	if v != nil {
		_u.SetMediaPath(*v)
	}
	return _u
}

// ClearMediaPath clears the value of the "media_path" field.
func (_u *AvatarUpdate) ClearMediaPath() *AvatarUpdate {
	_u.mutation.ClearMediaPath()
	return _u
}

// SetRemoteURL sets the "remote_url" field.
func (_u *AvatarUpdate) SetRemoteURL(v string) *AvatarUpdate {
	_u.mutation.SetRemoteURL(v)
	return _u
}

// SetNillableRemoteURL sets the "remote_url" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableRemoteURL(v *string) *AvatarUpdate {
	if v != nil {
		_u.SetRemoteURL(*v)
	}
	return _u
}

// ClearRemoteURL clears the value of the "remote_url" field.
func (_u *AvatarUpdate) ClearRemoteURL() *AvatarUpdate {
	_u.mutation.ClearRemoteURL()
	return _u
}

// SetCdnURL sets the "cdn_url" field.
func (_u *AvatarUpdate) SetCdnURL(v string) *AvatarUpdate {
	_u.mutation.SetCdnURL(v)
	return _u
}

// SetNillableCdnURL sets the "cdn_url" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableCdnURL(v *string) *AvatarUpdate {
	if v != nil {
		_u.SetCdnURL(*v)
	}
	return _u
}

// ClearCdnURL clears the value of the "cdn_url" field.
func (_u *AvatarUpdate) ClearCdnURL() *AvatarUpdate {
	_u.mutation.ClearCdnURL()
	return _u
}

// SetIsRemote sets the "is_remote" field.
func (_u *AvatarUpdate) SetIsRemote(v bool) *AvatarUpdate {
	_u.mutation.SetIsRemote(v)
	return _u
}

// SetNillableIsRemote sets the "is_remote" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableIsRemote(v *bool) *AvatarUpdate {
	if v != nil {
		_u.SetIsRemote(*v)
	}
	return _u
}

// ClearIsRemote clears the value of the "is_remote" field.
func (_u *AvatarUpdate) ClearIsRemote() *AvatarUpdate {
	_u.mutation.ClearIsRemote()
	return _u
}

// SetSize sets the "size" field.
func (_u *AvatarUpdate) SetSize(v uint) *AvatarUpdate {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableSize(v *uint) *AvatarUpdate {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *AvatarUpdate) AddSize(v int) *AvatarUpdate {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *AvatarUpdate) ClearSize() *AvatarUpdate {
	_u.mutation.ClearSize()
	return _u
}

// SetChangeCount sets the "change_count" field.
func (_u *AvatarUpdate) SetChangeCount(v uint) *AvatarUpdate {
	_u.mutation.ResetChangeCount()
	_u.mutation.SetChangeCount(v)
	return _u
}

// SetNillableChangeCount sets the "change_count" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableChangeCount(v *uint) *AvatarUpdate {
	if v != nil {
		_u.SetChangeCount(*v)
	}
	return _u
}

// AddChangeCount adds value to the "change_count" field.
func (_u *AvatarUpdate) AddChangeCount(v int) *AvatarUpdate {
	_u.mutation.AddChangeCount(v)
	return _u
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_u *AvatarUpdate) SetLastFetchedAt(v time.Time) *AvatarUpdate {
	_u.mutation.SetLastFetchedAt(v)
	return _u
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableLastFetchedAt(v *time.Time) *AvatarUpdate {
	if v != nil {
		_u.SetLastFetchedAt(*v)
	}
	return _u
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (_u *AvatarUpdate) ClearLastFetchedAt() *AvatarUpdate {
	_u.mutation.ClearLastFetchedAt()
	return _u
}

// SetLastProcessedAt sets the "last_processed_at" field.
func (_u *AvatarUpdate) SetLastProcessedAt(v time.Time) *AvatarUpdate {
	_u.mutation.SetLastProcessedAt(v)
	return _u
}

// SetNillableLastProcessedAt sets the "last_processed_at" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableLastProcessedAt(v *time.Time) *AvatarUpdate {
	if v != nil {
		_u.SetLastProcessedAt(*v)
	}
	return _u
}

// ClearLastProcessedAt clears the value of the "last_processed_at" field.
func (_u *AvatarUpdate) ClearLastProcessedAt() *AvatarUpdate {
	_u.mutation.ClearLastProcessedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AvatarUpdate) SetCreatedAt(v time.Time) *AvatarUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableCreatedAt(v *time.Time) *AvatarUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *AvatarUpdate) ClearCreatedAt() *AvatarUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AvatarUpdate) SetUpdatedAt(v time.Time) *AvatarUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableUpdatedAt(v *time.Time) *AvatarUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AvatarUpdate) ClearUpdatedAt() *AvatarUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AvatarUpdate) SetDeletedAt(v time.Time) *AvatarUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AvatarUpdate) SetNillableDeletedAt(v *time.Time) *AvatarUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AvatarUpdate) ClearDeletedAt() *AvatarUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_u *AvatarUpdate) SetProfile(v *Profile) *AvatarUpdate {
	return _u.SetProfileID(v.ID)
}

// Mutation returns the AvatarMutation object of the builder.
func (_u *AvatarUpdate) Mutation() *AvatarMutation {
	return _u.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (_u *AvatarUpdate) ClearProfile() *AvatarUpdate {
	_u.mutation.ClearProfile()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AvatarUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvatarUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AvatarUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvatarUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvatarUpdate) check() error {
	if _u.mutation.ProfileCleared() && len(_u.mutation.ProfileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Avatar.profile"`)
	}
	return nil
}

func (_u *AvatarUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(avatar.Table, avatar.Columns, sqlgraph.NewFieldSpec(avatar.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MediaPath(); ok {
		_spec.SetField(avatar.FieldMediaPath, field.TypeString, value)
	}
	if _u.mutation.MediaPathCleared() {
		_spec.ClearField(avatar.FieldMediaPath, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteURL(); ok {
		_spec.SetField(avatar.FieldRemoteURL, field.TypeString, value)
	}
	if _u.mutation.RemoteURLCleared() {
		_spec.ClearField(avatar.FieldRemoteURL, field.TypeString)
	}
	if value, ok := _u.mutation.CdnURL(); ok {
		_spec.SetField(avatar.FieldCdnURL, field.TypeString, value)
	}
	if _u.mutation.CdnURLCleared() {
		_spec.ClearField(avatar.FieldCdnURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsRemote(); ok {
		_spec.SetField(avatar.FieldIsRemote, field.TypeBool, value)
	}
	if _u.mutation.IsRemoteCleared() {
		_spec.ClearField(avatar.FieldIsRemote, field.TypeBool)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(avatar.FieldSize, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(avatar.FieldSize, field.TypeUint, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(avatar.FieldSize, field.TypeUint)
	}
	if value, ok := _u.mutation.ChangeCount(); ok {
		_spec.SetField(avatar.FieldChangeCount, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedChangeCount(); ok {
		_spec.AddField(avatar.FieldChangeCount, field.TypeUint, value)
	}
	if value, ok := _u.mutation.LastFetchedAt(); ok {
		_spec.SetField(avatar.FieldLastFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.LastFetchedAtCleared() {
		_spec.ClearField(avatar.FieldLastFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProcessedAt(); ok {
		_spec.SetField(avatar.FieldLastProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.LastProcessedAtCleared() {
		_spec.ClearField(avatar.FieldLastProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(avatar.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(avatar.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(avatar.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(avatar.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(avatar.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(avatar.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   avatar.ProfileTable,
			Columns: []string{avatar.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   avatar.ProfileTable,
			Columns: []string{avatar.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{avatar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AvatarUpdateOne is the builder for updating a single Avatar entity.
type AvatarUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AvatarMutation
}

// SetProfileID sets the "profile_id" field.
func (_u *AvatarUpdateOne) SetProfileID(v uint64) *AvatarUpdateOne {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableProfileID(v *uint64) *AvatarUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetMediaPath sets the "media_path" field.
func (_u *AvatarUpdateOne) SetMediaPath(v string) *AvatarUpdateOne {
	_u.mutation.SetMediaPath(v)
	return _u
}

// SetNillableMediaPath sets the "media_path" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableMediaPath(v *string) *AvatarUpdateOne {
	if v != nil {
		_u.SetMediaPath(*v)
	}
	return _u
}

// ClearMediaPath clears the value of the "media_path" field.
func (_u *AvatarUpdateOne) ClearMediaPath() *AvatarUpdateOne {
	_u.mutation.ClearMediaPath()
	return _u
}

// SetRemoteURL sets the "remote_url" field.
func (_u *AvatarUpdateOne) SetRemoteURL(v string) *AvatarUpdateOne {
	_u.mutation.SetRemoteURL(v)
	return _u
}

// SetNillableRemoteURL sets the "remote_url" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableRemoteURL(v *string) *AvatarUpdateOne {
	if v != nil {
		_u.SetRemoteURL(*v)
	}
	return _u
}

// ClearRemoteURL clears the value of the "remote_url" field.
func (_u *AvatarUpdateOne) ClearRemoteURL() *AvatarUpdateOne {
	_u.mutation.ClearRemoteURL()
	return _u
}

// SetCdnURL sets the "cdn_url" field.
func (_u *AvatarUpdateOne) SetCdnURL(v string) *AvatarUpdateOne {
	_u.mutation.SetCdnURL(v)
	return _u
}

// SetNillableCdnURL sets the "cdn_url" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableCdnURL(v *string) *AvatarUpdateOne {
	if v != nil {
		_u.SetCdnURL(*v)
	}
	return _u
}

// ClearCdnURL clears the value of the "cdn_url" field.
func (_u *AvatarUpdateOne) ClearCdnURL() *AvatarUpdateOne {
	_u.mutation.ClearCdnURL()
	return _u
}

// SetIsRemote sets the "is_remote" field.
func (_u *AvatarUpdateOne) SetIsRemote(v bool) *AvatarUpdateOne {
	_u.mutation.SetIsRemote(v)
	return _u
}

// SetNillableIsRemote sets the "is_remote" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableIsRemote(v *bool) *AvatarUpdateOne {
	if v != nil {
		_u.SetIsRemote(*v)
	}
	return _u
}

// ClearIsRemote clears the value of the "is_remote" field.
func (_u *AvatarUpdateOne) ClearIsRemote() *AvatarUpdateOne {
	_u.mutation.ClearIsRemote()
	return _u
}

// SetSize sets the "size" field.
func (_u *AvatarUpdateOne) SetSize(v uint) *AvatarUpdateOne {
	_u.mutation.ResetSize()
	_u.mutation.SetSize(v)
	return _u
}

// SetNillableSize sets the "size" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableSize(v *uint) *AvatarUpdateOne {
	if v != nil {
		_u.SetSize(*v)
	}
	return _u
}

// AddSize adds value to the "size" field.
func (_u *AvatarUpdateOne) AddSize(v int) *AvatarUpdateOne {
	_u.mutation.AddSize(v)
	return _u
}

// ClearSize clears the value of the "size" field.
func (_u *AvatarUpdateOne) ClearSize() *AvatarUpdateOne {
	_u.mutation.ClearSize()
	return _u
}

// SetChangeCount sets the "change_count" field.
func (_u *AvatarUpdateOne) SetChangeCount(v uint) *AvatarUpdateOne {
	_u.mutation.ResetChangeCount()
	_u.mutation.SetChangeCount(v)
	return _u
}

// SetNillableChangeCount sets the "change_count" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableChangeCount(v *uint) *AvatarUpdateOne {
	if v != nil {
		_u.SetChangeCount(*v)
	}
	return _u
}

// AddChangeCount adds value to the "change_count" field.
func (_u *AvatarUpdateOne) AddChangeCount(v int) *AvatarUpdateOne {
	_u.mutation.AddChangeCount(v)
	return _u
}

// SetLastFetchedAt sets the "last_fetched_at" field.
func (_u *AvatarUpdateOne) SetLastFetchedAt(v time.Time) *AvatarUpdateOne {
	_u.mutation.SetLastFetchedAt(v)
	return _u
}

// SetNillableLastFetchedAt sets the "last_fetched_at" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableLastFetchedAt(v *time.Time) *AvatarUpdateOne {
	if v != nil {
		_u.SetLastFetchedAt(*v)
	}
	return _u
}

// ClearLastFetchedAt clears the value of the "last_fetched_at" field.
func (_u *AvatarUpdateOne) ClearLastFetchedAt() *AvatarUpdateOne {
	_u.mutation.ClearLastFetchedAt()
	return _u
}

// SetLastProcessedAt sets the "last_processed_at" field.
func (_u *AvatarUpdateOne) SetLastProcessedAt(v time.Time) *AvatarUpdateOne {
	_u.mutation.SetLastProcessedAt(v)
	return _u
}

// SetNillableLastProcessedAt sets the "last_processed_at" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableLastProcessedAt(v *time.Time) *AvatarUpdateOne {
	if v != nil {
		_u.SetLastProcessedAt(*v)
	}
	return _u
}

// ClearLastProcessedAt clears the value of the "last_processed_at" field.
func (_u *AvatarUpdateOne) ClearLastProcessedAt() *AvatarUpdateOne {
	_u.mutation.ClearLastProcessedAt()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *AvatarUpdateOne) SetCreatedAt(v time.Time) *AvatarUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableCreatedAt(v *time.Time) *AvatarUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *AvatarUpdateOne) ClearCreatedAt() *AvatarUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AvatarUpdateOne) SetUpdatedAt(v time.Time) *AvatarUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableUpdatedAt(v *time.Time) *AvatarUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *AvatarUpdateOne) ClearUpdatedAt() *AvatarUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *AvatarUpdateOne) SetDeletedAt(v time.Time) *AvatarUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *AvatarUpdateOne) SetNillableDeletedAt(v *time.Time) *AvatarUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *AvatarUpdateOne) ClearDeletedAt() *AvatarUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_u *AvatarUpdateOne) SetProfile(v *Profile) *AvatarUpdateOne {
	return _u.SetProfileID(v.ID)
}

// Mutation returns the AvatarMutation object of the builder.
func (_u *AvatarUpdateOne) Mutation() *AvatarMutation {
	return _u.mutation
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (_u *AvatarUpdateOne) ClearProfile() *AvatarUpdateOne {
	_u.mutation.ClearProfile()
	return _u
}

// Where appends a list predicates to the AvatarUpdate builder.
func (_u *AvatarUpdateOne) Where(ps ...predicate.Avatar) *AvatarUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AvatarUpdateOne) Select(field string, fields ...string) *AvatarUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Avatar entity.
func (_u *AvatarUpdateOne) Save(ctx context.Context) (*Avatar, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AvatarUpdateOne) SaveX(ctx context.Context) *Avatar {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AvatarUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AvatarUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AvatarUpdateOne) check() error {
	if _u.mutation.ProfileCleared() && len(_u.mutation.ProfileIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Avatar.profile"`)
	}
	return nil
}

func (_u *AvatarUpdateOne) sqlSave(ctx context.Context) (_node *Avatar, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(avatar.Table, avatar.Columns, sqlgraph.NewFieldSpec(avatar.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Avatar.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, avatar.FieldID)
		for _, f := range fields {
			if !avatar.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != avatar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.MediaPath(); ok {
		_spec.SetField(avatar.FieldMediaPath, field.TypeString, value)
	}
	if _u.mutation.MediaPathCleared() {
		_spec.ClearField(avatar.FieldMediaPath, field.TypeString)
	}
	if value, ok := _u.mutation.RemoteURL(); ok {
		_spec.SetField(avatar.FieldRemoteURL, field.TypeString, value)
	}
	if _u.mutation.RemoteURLCleared() {
		_spec.ClearField(avatar.FieldRemoteURL, field.TypeString)
	}
	if value, ok := _u.mutation.CdnURL(); ok {
		_spec.SetField(avatar.FieldCdnURL, field.TypeString, value)
	}
	if _u.mutation.CdnURLCleared() {
		_spec.ClearField(avatar.FieldCdnURL, field.TypeString)
	}
	if value, ok := _u.mutation.IsRemote(); ok {
		_spec.SetField(avatar.FieldIsRemote, field.TypeBool, value)
	}
	if _u.mutation.IsRemoteCleared() {
		_spec.ClearField(avatar.FieldIsRemote, field.TypeBool)
	}
	if value, ok := _u.mutation.Size(); ok {
		_spec.SetField(avatar.FieldSize, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedSize(); ok {
		_spec.AddField(avatar.FieldSize, field.TypeUint, value)
	}
	if _u.mutation.SizeCleared() {
		_spec.ClearField(avatar.FieldSize, field.TypeUint)
	}
	if value, ok := _u.mutation.ChangeCount(); ok {
		_spec.SetField(avatar.FieldChangeCount, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedChangeCount(); ok {
		_spec.AddField(avatar.FieldChangeCount, field.TypeUint, value)
	}
	if value, ok := _u.mutation.LastFetchedAt(); ok {
		_spec.SetField(avatar.FieldLastFetchedAt, field.TypeTime, value)
	}
	if _u.mutation.LastFetchedAtCleared() {
		_spec.ClearField(avatar.FieldLastFetchedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProcessedAt(); ok {
		_spec.SetField(avatar.FieldLastProcessedAt, field.TypeTime, value)
	}
	if _u.mutation.LastProcessedAtCleared() {
		_spec.ClearField(avatar.FieldLastProcessedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(avatar.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(avatar.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(avatar.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(avatar.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(avatar.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(avatar.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   avatar.ProfileTable,
			Columns: []string{avatar.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   avatar.ProfileTable,
			Columns: []string{avatar.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Avatar{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{avatar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
