// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"glintfed/ent/cache"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Cache is the model entity for the Cache schema.
type Cache struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Key holds the value of the "key" field.
	Key string `json:"key,omitempty"`
	// Value holds the value of the "value" field.
	Value string `json:"value,omitempty"`
	// Expiration holds the value of the "expiration" field.
	Expiration   int `json:"expiration,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Cache) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case cache.FieldID, cache.FieldExpiration:
			values[i] = new(sql.NullInt64)
		case cache.FieldKey, cache.FieldValue:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Cache fields.
func (_m *Cache) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case cache.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case cache.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case cache.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case cache.FieldExpiration:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field expiration", values[i])
			} else if value.Valid {
				_m.Expiration = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the Cache.
// This includes values selected through modifiers, order, etc.
func (_m *Cache) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this Cache.
// Note that you need to call Cache.Unwrap() before calling this method if this Cache
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Cache) Update() *CacheUpdateOne {
	return NewCacheClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Cache entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Cache) Unwrap() *Cache {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Cache is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Cache) String() string {
	var builder strings.Builder
	builder.WriteString("Cache(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("value=")
	builder.WriteString(_m.Value)
	builder.WriteString(", ")
	builder.WriteString("expiration=")
	builder.WriteString(fmt.Sprintf("%v", _m.Expiration))
	builder.WriteByte(')')
	return builder.String()
}

// Caches is a parsable slice of Cache.
type Caches []*Cache
