// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/customemojicategory"
	"glintfed/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomEmojiCategoryUpdate is the builder for updating CustomEmojiCategory entities.
type CustomEmojiCategoryUpdate struct {
	config
	hooks    []Hook
	mutation *CustomEmojiCategoryMutation
}

// Where appends a list predicates to the CustomEmojiCategoryUpdate builder.
func (_u *CustomEmojiCategoryUpdate) Where(ps ...predicate.CustomEmojiCategory) *CustomEmojiCategoryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *CustomEmojiCategoryUpdate) SetName(v string) *CustomEmojiCategoryUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomEmojiCategoryUpdate) SetNillableName(v *string) *CustomEmojiCategoryUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *CustomEmojiCategoryUpdate) SetDisabled(v bool) *CustomEmojiCategoryUpdate {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *CustomEmojiCategoryUpdate) SetNillableDisabled(v *bool) *CustomEmojiCategoryUpdate {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CustomEmojiCategoryUpdate) SetCreatedAt(v time.Time) *CustomEmojiCategoryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CustomEmojiCategoryUpdate) SetNillableCreatedAt(v *time.Time) *CustomEmojiCategoryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *CustomEmojiCategoryUpdate) ClearCreatedAt() *CustomEmojiCategoryUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomEmojiCategoryUpdate) SetUpdatedAt(v time.Time) *CustomEmojiCategoryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *CustomEmojiCategoryUpdate) SetNillableUpdatedAt(v *time.Time) *CustomEmojiCategoryUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *CustomEmojiCategoryUpdate) ClearUpdatedAt() *CustomEmojiCategoryUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the CustomEmojiCategoryMutation object of the builder.
func (_u *CustomEmojiCategoryUpdate) Mutation() *CustomEmojiCategoryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CustomEmojiCategoryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomEmojiCategoryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CustomEmojiCategoryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomEmojiCategoryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CustomEmojiCategoryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(customemojicategory.Table, customemojicategory.Columns, sqlgraph.NewFieldSpec(customemojicategory.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(customemojicategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(customemojicategory.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(customemojicategory.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(customemojicategory.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customemojicategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(customemojicategory.FieldUpdatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customemojicategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CustomEmojiCategoryUpdateOne is the builder for updating a single CustomEmojiCategory entity.
type CustomEmojiCategoryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CustomEmojiCategoryMutation
}

// SetName sets the "name" field.
func (_u *CustomEmojiCategoryUpdateOne) SetName(v string) *CustomEmojiCategoryUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *CustomEmojiCategoryUpdateOne) SetNillableName(v *string) *CustomEmojiCategoryUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDisabled sets the "disabled" field.
func (_u *CustomEmojiCategoryUpdateOne) SetDisabled(v bool) *CustomEmojiCategoryUpdateOne {
	_u.mutation.SetDisabled(v)
	return _u
}

// SetNillableDisabled sets the "disabled" field if the given value is not nil.
func (_u *CustomEmojiCategoryUpdateOne) SetNillableDisabled(v *bool) *CustomEmojiCategoryUpdateOne {
	if v != nil {
		_u.SetDisabled(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *CustomEmojiCategoryUpdateOne) SetCreatedAt(v time.Time) *CustomEmojiCategoryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *CustomEmojiCategoryUpdateOne) SetNillableCreatedAt(v *time.Time) *CustomEmojiCategoryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *CustomEmojiCategoryUpdateOne) ClearCreatedAt() *CustomEmojiCategoryUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CustomEmojiCategoryUpdateOne) SetUpdatedAt(v time.Time) *CustomEmojiCategoryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *CustomEmojiCategoryUpdateOne) SetNillableUpdatedAt(v *time.Time) *CustomEmojiCategoryUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *CustomEmojiCategoryUpdateOne) ClearUpdatedAt() *CustomEmojiCategoryUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the CustomEmojiCategoryMutation object of the builder.
func (_u *CustomEmojiCategoryUpdateOne) Mutation() *CustomEmojiCategoryMutation {
	return _u.mutation
}

// Where appends a list predicates to the CustomEmojiCategoryUpdate builder.
func (_u *CustomEmojiCategoryUpdateOne) Where(ps ...predicate.CustomEmojiCategory) *CustomEmojiCategoryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CustomEmojiCategoryUpdateOne) Select(field string, fields ...string) *CustomEmojiCategoryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CustomEmojiCategory entity.
func (_u *CustomEmojiCategoryUpdateOne) Save(ctx context.Context) (*CustomEmojiCategory, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CustomEmojiCategoryUpdateOne) SaveX(ctx context.Context) *CustomEmojiCategory {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CustomEmojiCategoryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CustomEmojiCategoryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *CustomEmojiCategoryUpdateOne) sqlSave(ctx context.Context) (_node *CustomEmojiCategory, err error) {
	_spec := sqlgraph.NewUpdateSpec(customemojicategory.Table, customemojicategory.Columns, sqlgraph.NewFieldSpec(customemojicategory.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CustomEmojiCategory.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, customemojicategory.FieldID)
		for _, f := range fields {
			if !customemojicategory.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != customemojicategory.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(customemojicategory.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Disabled(); ok {
		_spec.SetField(customemojicategory.FieldDisabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(customemojicategory.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(customemojicategory.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(customemojicategory.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(customemojicategory.FieldUpdatedAt, field.TypeTime)
	}
	_node = &CustomEmojiCategory{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{customemojicategory.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
