// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/customfilter"
	"glintfed/ent/customfilterstatus"
	"glintfed/ent/status"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CustomFilterStatusCreate is the builder for creating a CustomFilterStatus entity.
type CustomFilterStatusCreate struct {
	config
	mutation *CustomFilterStatusMutation
	hooks    []Hook
}

// SetCustomFilterID sets the "custom_filter_id" field.
func (_c *CustomFilterStatusCreate) SetCustomFilterID(v uint64) *CustomFilterStatusCreate {
	_c.mutation.SetCustomFilterID(v)
	return _c
}

// SetStatusID sets the "status_id" field.
func (_c *CustomFilterStatusCreate) SetStatusID(v uint64) *CustomFilterStatusCreate {
	_c.mutation.SetStatusID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *CustomFilterStatusCreate) SetCreatedAt(v time.Time) *CustomFilterStatusCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *CustomFilterStatusCreate) SetNillableCreatedAt(v *time.Time) *CustomFilterStatusCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *CustomFilterStatusCreate) SetUpdatedAt(v time.Time) *CustomFilterStatusCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *CustomFilterStatusCreate) SetNillableUpdatedAt(v *time.Time) *CustomFilterStatusCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *CustomFilterStatusCreate) SetID(v uint64) *CustomFilterStatusCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetCustomFilter sets the "customFilter" edge to the CustomFilter entity.
func (_c *CustomFilterStatusCreate) SetCustomFilter(v *CustomFilter) *CustomFilterStatusCreate {
	return _c.SetCustomFilterID(v.ID)
}

// SetStatus sets the "status" edge to the Status entity.
func (_c *CustomFilterStatusCreate) SetStatus(v *Status) *CustomFilterStatusCreate {
	return _c.SetStatusID(v.ID)
}

// Mutation returns the CustomFilterStatusMutation object of the builder.
func (_c *CustomFilterStatusCreate) Mutation() *CustomFilterStatusMutation {
	return _c.mutation
}

// Save creates the CustomFilterStatus in the database.
func (_c *CustomFilterStatusCreate) Save(ctx context.Context) (*CustomFilterStatus, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *CustomFilterStatusCreate) SaveX(ctx context.Context) *CustomFilterStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomFilterStatusCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomFilterStatusCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *CustomFilterStatusCreate) check() error {
	if _, ok := _c.mutation.CustomFilterID(); !ok {
		return &ValidationError{Name: "custom_filter_id", err: errors.New(`ent: missing required field "CustomFilterStatus.custom_filter_id"`)}
	}
	if _, ok := _c.mutation.StatusID(); !ok {
		return &ValidationError{Name: "status_id", err: errors.New(`ent: missing required field "CustomFilterStatus.status_id"`)}
	}
	if len(_c.mutation.CustomFilterIDs()) == 0 {
		return &ValidationError{Name: "customFilter", err: errors.New(`ent: missing required edge "CustomFilterStatus.customFilter"`)}
	}
	if len(_c.mutation.StatusIDs()) == 0 {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required edge "CustomFilterStatus.status"`)}
	}
	return nil
}

func (_c *CustomFilterStatusCreate) sqlSave(ctx context.Context) (*CustomFilterStatus, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *CustomFilterStatusCreate) createSpec() (*CustomFilterStatus, *sqlgraph.CreateSpec) {
	var (
		_node = &CustomFilterStatus{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(customfilterstatus.Table, sqlgraph.NewFieldSpec(customfilterstatus.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(customfilterstatus.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(customfilterstatus.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if nodes := _c.mutation.CustomFilterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   customfilterstatus.CustomFilterTable,
			Columns: []string{customfilterstatus.CustomFilterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(customfilter.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.CustomFilterID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   customfilterstatus.StatusTable,
			Columns: []string{customfilterstatus.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.StatusID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// CustomFilterStatusCreateBulk is the builder for creating many CustomFilterStatus entities in bulk.
type CustomFilterStatusCreateBulk struct {
	config
	err      error
	builders []*CustomFilterStatusCreate
}

// Save creates the CustomFilterStatus entities in the database.
func (_c *CustomFilterStatusCreateBulk) Save(ctx context.Context) ([]*CustomFilterStatus, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*CustomFilterStatus, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*CustomFilterStatusMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *CustomFilterStatusCreateBulk) SaveX(ctx context.Context) []*CustomFilterStatus {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *CustomFilterStatusCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *CustomFilterStatusCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
