// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/emailverification"
	"glintfed/ent/predicate"
	"glintfed/ent/user"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EmailVerificationUpdate is the builder for updating EmailVerification entities.
type EmailVerificationUpdate struct {
	config
	hooks    []Hook
	mutation *EmailVerificationMutation
}

// Where appends a list predicates to the EmailVerificationUpdate builder.
func (_u *EmailVerificationUpdate) Where(ps ...predicate.EmailVerification) *EmailVerificationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *EmailVerificationUpdate) SetUserID(v uint64) *EmailVerificationUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableUserID(v *uint64) *EmailVerificationUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmailVerificationUpdate) SetEmail(v string) *EmailVerificationUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableEmail(v *string) *EmailVerificationUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *EmailVerificationUpdate) ClearEmail() *EmailVerificationUpdate {
	_u.mutation.ClearEmail()
	return _u
}

// SetUserToken sets the "user_token" field.
func (_u *EmailVerificationUpdate) SetUserToken(v string) *EmailVerificationUpdate {
	_u.mutation.SetUserToken(v)
	return _u
}

// SetNillableUserToken sets the "user_token" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableUserToken(v *string) *EmailVerificationUpdate {
	if v != nil {
		_u.SetUserToken(*v)
	}
	return _u
}

// SetRandomToken sets the "random_token" field.
func (_u *EmailVerificationUpdate) SetRandomToken(v string) *EmailVerificationUpdate {
	_u.mutation.SetRandomToken(v)
	return _u
}

// SetNillableRandomToken sets the "random_token" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableRandomToken(v *string) *EmailVerificationUpdate {
	if v != nil {
		_u.SetRandomToken(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EmailVerificationUpdate) SetCreatedAt(v time.Time) *EmailVerificationUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableCreatedAt(v *time.Time) *EmailVerificationUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *EmailVerificationUpdate) ClearCreatedAt() *EmailVerificationUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailVerificationUpdate) SetUpdatedAt(v time.Time) *EmailVerificationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *EmailVerificationUpdate) SetNillableUpdatedAt(v *time.Time) *EmailVerificationUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *EmailVerificationUpdate) ClearUpdatedAt() *EmailVerificationUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EmailVerificationUpdate) SetUser(v *User) *EmailVerificationUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the EmailVerificationMutation object of the builder.
func (_u *EmailVerificationUpdate) Mutation() *EmailVerificationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EmailVerificationUpdate) ClearUser() *EmailVerificationUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EmailVerificationUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailVerificationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EmailVerificationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailVerificationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailVerificationUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailVerification.user"`)
	}
	return nil
}

func (_u *EmailVerificationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailverification.Table, emailverification.Columns, sqlgraph.NewFieldSpec(emailverification.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailverification.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(emailverification.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UserToken(); ok {
		_spec.SetField(emailverification.FieldUserToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RandomToken(); ok {
		_spec.SetField(emailverification.FieldRandomToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(emailverification.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(emailverification.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailverification.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(emailverification.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   emailverification.UserTable,
			Columns: []string{emailverification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   emailverification.UserTable,
			Columns: []string{emailverification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EmailVerificationUpdateOne is the builder for updating a single EmailVerification entity.
type EmailVerificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EmailVerificationMutation
}

// SetUserID sets the "user_id" field.
func (_u *EmailVerificationUpdateOne) SetUserID(v uint64) *EmailVerificationUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableUserID(v *uint64) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetEmail sets the "email" field.
func (_u *EmailVerificationUpdateOne) SetEmail(v string) *EmailVerificationUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableEmail(v *string) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// ClearEmail clears the value of the "email" field.
func (_u *EmailVerificationUpdateOne) ClearEmail() *EmailVerificationUpdateOne {
	_u.mutation.ClearEmail()
	return _u
}

// SetUserToken sets the "user_token" field.
func (_u *EmailVerificationUpdateOne) SetUserToken(v string) *EmailVerificationUpdateOne {
	_u.mutation.SetUserToken(v)
	return _u
}

// SetNillableUserToken sets the "user_token" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableUserToken(v *string) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetUserToken(*v)
	}
	return _u
}

// SetRandomToken sets the "random_token" field.
func (_u *EmailVerificationUpdateOne) SetRandomToken(v string) *EmailVerificationUpdateOne {
	_u.mutation.SetRandomToken(v)
	return _u
}

// SetNillableRandomToken sets the "random_token" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableRandomToken(v *string) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetRandomToken(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *EmailVerificationUpdateOne) SetCreatedAt(v time.Time) *EmailVerificationUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableCreatedAt(v *time.Time) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *EmailVerificationUpdateOne) ClearCreatedAt() *EmailVerificationUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EmailVerificationUpdateOne) SetUpdatedAt(v time.Time) *EmailVerificationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *EmailVerificationUpdateOne) SetNillableUpdatedAt(v *time.Time) *EmailVerificationUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *EmailVerificationUpdateOne) ClearUpdatedAt() *EmailVerificationUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *EmailVerificationUpdateOne) SetUser(v *User) *EmailVerificationUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the EmailVerificationMutation object of the builder.
func (_u *EmailVerificationUpdateOne) Mutation() *EmailVerificationMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *EmailVerificationUpdateOne) ClearUser() *EmailVerificationUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the EmailVerificationUpdate builder.
func (_u *EmailVerificationUpdateOne) Where(ps ...predicate.EmailVerification) *EmailVerificationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EmailVerificationUpdateOne) Select(field string, fields ...string) *EmailVerificationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EmailVerification entity.
func (_u *EmailVerificationUpdateOne) Save(ctx context.Context) (*EmailVerification, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EmailVerificationUpdateOne) SaveX(ctx context.Context) *EmailVerification {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EmailVerificationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EmailVerificationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EmailVerificationUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "EmailVerification.user"`)
	}
	return nil
}

func (_u *EmailVerificationUpdateOne) sqlSave(ctx context.Context) (_node *EmailVerification, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(emailverification.Table, emailverification.Columns, sqlgraph.NewFieldSpec(emailverification.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "EmailVerification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, emailverification.FieldID)
		for _, f := range fields {
			if !emailverification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != emailverification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(emailverification.FieldEmail, field.TypeString, value)
	}
	if _u.mutation.EmailCleared() {
		_spec.ClearField(emailverification.FieldEmail, field.TypeString)
	}
	if value, ok := _u.mutation.UserToken(); ok {
		_spec.SetField(emailverification.FieldUserToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.RandomToken(); ok {
		_spec.SetField(emailverification.FieldRandomToken, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(emailverification.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(emailverification.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(emailverification.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(emailverification.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   emailverification.UserTable,
			Columns: []string{emailverification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   emailverification.UserTable,
			Columns: []string{emailverification.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EmailVerification{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{emailverification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
