// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"glintfed/ent/groupevent"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GroupEvent is the model entity for the GroupEvent schema.
type GroupEvent struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID *uint64 `json:"group_id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID *uint64 `json:"profile_id,omitempty"`
	// Name holds the value of the "name" field.
	Name *string `json:"name,omitempty"`
	// Type holds the value of the "type" field.
	Type string `json:"type,omitempty"`
	// Tags holds the value of the "tags" field.
	Tags *string `json:"tags,omitempty"`
	// Location holds the value of the "location" field.
	Location *string `json:"location,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata *string `json:"metadata,omitempty"`
	// Open holds the value of the "open" field.
	Open bool `json:"open,omitempty"`
	// CommentsOpen holds the value of the "comments_open" field.
	CommentsOpen bool `json:"comments_open,omitempty"`
	// ShowGuestList holds the value of the "show_guest_list" field.
	ShowGuestList bool `json:"show_guest_list,omitempty"`
	// StartAt holds the value of the "start_at" field.
	StartAt *time.Time `json:"start_at,omitempty"`
	// EndAt holds the value of the "end_at" field.
	EndAt *time.Time `json:"end_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupEvent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupevent.FieldOpen, groupevent.FieldCommentsOpen, groupevent.FieldShowGuestList:
			values[i] = new(sql.NullBool)
		case groupevent.FieldID, groupevent.FieldGroupID, groupevent.FieldProfileID:
			values[i] = new(sql.NullInt64)
		case groupevent.FieldName, groupevent.FieldType, groupevent.FieldTags, groupevent.FieldLocation, groupevent.FieldDescription, groupevent.FieldMetadata:
			values[i] = new(sql.NullString)
		case groupevent.FieldStartAt, groupevent.FieldEndAt, groupevent.FieldCreatedAt, groupevent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupEvent fields.
func (_m *GroupEvent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupevent.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case groupevent.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = new(uint64)
				*_m.GroupID = uint64(value.Int64)
			}
		case groupevent.FieldProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = new(uint64)
				*_m.ProfileID = uint64(value.Int64)
			}
		case groupevent.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = new(string)
				*_m.Name = value.String
			}
		case groupevent.FieldType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				_m.Type = value.String
			}
		case groupevent.FieldTags:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tags", values[i])
			} else if value.Valid {
				_m.Tags = new(string)
				*_m.Tags = value.String
			}
		case groupevent.FieldLocation:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field location", values[i])
			} else if value.Valid {
				_m.Location = new(string)
				*_m.Location = value.String
			}
		case groupevent.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case groupevent.FieldMetadata:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value.Valid {
				_m.Metadata = new(string)
				*_m.Metadata = value.String
			}
		case groupevent.FieldOpen:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field open", values[i])
			} else if value.Valid {
				_m.Open = value.Bool
			}
		case groupevent.FieldCommentsOpen:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field comments_open", values[i])
			} else if value.Valid {
				_m.CommentsOpen = value.Bool
			}
		case groupevent.FieldShowGuestList:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field show_guest_list", values[i])
			} else if value.Valid {
				_m.ShowGuestList = value.Bool
			}
		case groupevent.FieldStartAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field start_at", values[i])
			} else if value.Valid {
				_m.StartAt = new(time.Time)
				*_m.StartAt = value.Time
			}
		case groupevent.FieldEndAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field end_at", values[i])
			} else if value.Valid {
				_m.EndAt = new(time.Time)
				*_m.EndAt = value.Time
			}
		case groupevent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case groupevent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupEvent.
// This includes values selected through modifiers, order, etc.
func (_m *GroupEvent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GroupEvent.
// Note that you need to call GroupEvent.Unwrap() before calling this method if this GroupEvent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupEvent) Update() *GroupEventUpdateOne {
	return NewGroupEventClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupEvent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupEvent) Unwrap() *GroupEvent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupEvent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupEvent) String() string {
	var builder strings.Builder
	builder.WriteString("GroupEvent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.GroupID; v != nil {
		builder.WriteString("group_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ProfileID; v != nil {
		builder.WriteString("profile_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Name; v != nil {
		builder.WriteString("name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(_m.Type)
	builder.WriteString(", ")
	if v := _m.Tags; v != nil {
		builder.WriteString("tags=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Location; v != nil {
		builder.WriteString("location=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Metadata; v != nil {
		builder.WriteString("metadata=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("open=")
	builder.WriteString(fmt.Sprintf("%v", _m.Open))
	builder.WriteString(", ")
	builder.WriteString("comments_open=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommentsOpen))
	builder.WriteString(", ")
	builder.WriteString("show_guest_list=")
	builder.WriteString(fmt.Sprintf("%v", _m.ShowGuestList))
	builder.WriteString(", ")
	if v := _m.StartAt; v != nil {
		builder.WriteString("start_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.EndAt; v != nil {
		builder.WriteString("end_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GroupEvents is a parsable slice of GroupEvent.
type GroupEvents []*GroupEvent
