// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"glintfed/ent/groupmedia"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GroupMedia is the model entity for the GroupMedia schema.
type GroupMedia struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// GroupID holds the value of the "group_id" field.
	GroupID uint64 `json:"group_id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID uint64 `json:"profile_id,omitempty"`
	// StatusID holds the value of the "status_id" field.
	StatusID *uint64 `json:"status_id,omitempty"`
	// MediaPath holds the value of the "media_path" field.
	MediaPath string `json:"media_path,omitempty"`
	// ThumbnailURL holds the value of the "thumbnail_url" field.
	ThumbnailURL *string `json:"thumbnail_url,omitempty"`
	// CdnURL holds the value of the "cdn_url" field.
	CdnURL *string `json:"cdn_url,omitempty"`
	// URL holds the value of the "url" field.
	URL *string `json:"url,omitempty"`
	// Mime holds the value of the "mime" field.
	Mime *string `json:"mime,omitempty"`
	// Size holds the value of the "size" field.
	Size *uint `json:"size,omitempty"`
	// CwSummary holds the value of the "cw_summary" field.
	CwSummary *string `json:"cw_summary,omitempty"`
	// License holds the value of the "license" field.
	License *string `json:"license,omitempty"`
	// Blurhash holds the value of the "blurhash" field.
	Blurhash *string `json:"blurhash,omitempty"`
	// Order holds the value of the "order" field.
	Order uint `json:"order,omitempty"`
	// Width holds the value of the "width" field.
	Width *uint `json:"width,omitempty"`
	// Height holds the value of the "height" field.
	Height *uint `json:"height,omitempty"`
	// LocalUser holds the value of the "local_user" field.
	LocalUser bool `json:"local_user,omitempty"`
	// IsCached holds the value of the "is_cached" field.
	IsCached bool `json:"is_cached,omitempty"`
	// IsComment holds the value of the "is_comment" field.
	IsComment bool `json:"is_comment,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata *string `json:"metadata,omitempty"`
	// Version holds the value of the "version" field.
	Version string `json:"version,omitempty"`
	// SkipOptimize holds the value of the "skip_optimize" field.
	SkipOptimize bool `json:"skip_optimize,omitempty"`
	// ProcessedAt holds the value of the "processed_at" field.
	ProcessedAt *time.Time `json:"processed_at,omitempty"`
	// ThumbnailGenerated holds the value of the "thumbnail_generated" field.
	ThumbnailGenerated *time.Time `json:"thumbnail_generated,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupMedia) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case groupmedia.FieldLocalUser, groupmedia.FieldIsCached, groupmedia.FieldIsComment, groupmedia.FieldSkipOptimize:
			values[i] = new(sql.NullBool)
		case groupmedia.FieldID, groupmedia.FieldGroupID, groupmedia.FieldProfileID, groupmedia.FieldStatusID, groupmedia.FieldSize, groupmedia.FieldOrder, groupmedia.FieldWidth, groupmedia.FieldHeight:
			values[i] = new(sql.NullInt64)
		case groupmedia.FieldMediaPath, groupmedia.FieldThumbnailURL, groupmedia.FieldCdnURL, groupmedia.FieldURL, groupmedia.FieldMime, groupmedia.FieldCwSummary, groupmedia.FieldLicense, groupmedia.FieldBlurhash, groupmedia.FieldMetadata, groupmedia.FieldVersion:
			values[i] = new(sql.NullString)
		case groupmedia.FieldProcessedAt, groupmedia.FieldThumbnailGenerated, groupmedia.FieldCreatedAt, groupmedia.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupMedia fields.
func (_m *GroupMedia) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case groupmedia.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case groupmedia.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				_m.GroupID = uint64(value.Int64)
			}
		case groupmedia.FieldProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = uint64(value.Int64)
			}
		case groupmedia.FieldStatusID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_id", values[i])
			} else if value.Valid {
				_m.StatusID = new(uint64)
				*_m.StatusID = uint64(value.Int64)
			}
		case groupmedia.FieldMediaPath:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_path", values[i])
			} else if value.Valid {
				_m.MediaPath = value.String
			}
		case groupmedia.FieldThumbnailURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_url", values[i])
			} else if value.Valid {
				_m.ThumbnailURL = new(string)
				*_m.ThumbnailURL = value.String
			}
		case groupmedia.FieldCdnURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cdn_url", values[i])
			} else if value.Valid {
				_m.CdnURL = new(string)
				*_m.CdnURL = value.String
			}
		case groupmedia.FieldURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field url", values[i])
			} else if value.Valid {
				_m.URL = new(string)
				*_m.URL = value.String
			}
		case groupmedia.FieldMime:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mime", values[i])
			} else if value.Valid {
				_m.Mime = new(string)
				*_m.Mime = value.String
			}
		case groupmedia.FieldSize:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field size", values[i])
			} else if value.Valid {
				_m.Size = new(uint)
				*_m.Size = uint(value.Int64)
			}
		case groupmedia.FieldCwSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cw_summary", values[i])
			} else if value.Valid {
				_m.CwSummary = new(string)
				*_m.CwSummary = value.String
			}
		case groupmedia.FieldLicense:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field license", values[i])
			} else if value.Valid {
				_m.License = new(string)
				*_m.License = value.String
			}
		case groupmedia.FieldBlurhash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blurhash", values[i])
			} else if value.Valid {
				_m.Blurhash = new(string)
				*_m.Blurhash = value.String
			}
		case groupmedia.FieldOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order", values[i])
			} else if value.Valid {
				_m.Order = uint(value.Int64)
			}
		case groupmedia.FieldWidth:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field width", values[i])
			} else if value.Valid {
				_m.Width = new(uint)
				*_m.Width = uint(value.Int64)
			}
		case groupmedia.FieldHeight:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field height", values[i])
			} else if value.Valid {
				_m.Height = new(uint)
				*_m.Height = uint(value.Int64)
			}
		case groupmedia.FieldLocalUser:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field local_user", values[i])
			} else if value.Valid {
				_m.LocalUser = value.Bool
			}
		case groupmedia.FieldIsCached:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_cached", values[i])
			} else if value.Valid {
				_m.IsCached = value.Bool
			}
		case groupmedia.FieldIsComment:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_comment", values[i])
			} else if value.Valid {
				_m.IsComment = value.Bool
			}
		case groupmedia.FieldMetadata:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value.Valid {
				_m.Metadata = new(string)
				*_m.Metadata = value.String
			}
		case groupmedia.FieldVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.String
			}
		case groupmedia.FieldSkipOptimize:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field skip_optimize", values[i])
			} else if value.Valid {
				_m.SkipOptimize = value.Bool
			}
		case groupmedia.FieldProcessedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field processed_at", values[i])
			} else if value.Valid {
				_m.ProcessedAt = new(time.Time)
				*_m.ProcessedAt = value.Time
			}
		case groupmedia.FieldThumbnailGenerated:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field thumbnail_generated", values[i])
			} else if value.Valid {
				_m.ThumbnailGenerated = new(time.Time)
				*_m.ThumbnailGenerated = value.Time
			}
		case groupmedia.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case groupmedia.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupMedia.
// This includes values selected through modifiers, order, etc.
func (_m *GroupMedia) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this GroupMedia.
// Note that you need to call GroupMedia.Unwrap() before calling this method if this GroupMedia
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *GroupMedia) Update() *GroupMediaUpdateOne {
	return NewGroupMediaClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the GroupMedia entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *GroupMedia) Unwrap() *GroupMedia {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupMedia is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *GroupMedia) String() string {
	var builder strings.Builder
	builder.WriteString("GroupMedia(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.GroupID))
	builder.WriteString(", ")
	builder.WriteString("profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProfileID))
	builder.WriteString(", ")
	if v := _m.StatusID; v != nil {
		builder.WriteString("status_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("media_path=")
	builder.WriteString(_m.MediaPath)
	builder.WriteString(", ")
	if v := _m.ThumbnailURL; v != nil {
		builder.WriteString("thumbnail_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CdnURL; v != nil {
		builder.WriteString("cdn_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.URL; v != nil {
		builder.WriteString("url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Mime; v != nil {
		builder.WriteString("mime=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Size; v != nil {
		builder.WriteString("size=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CwSummary; v != nil {
		builder.WriteString("cw_summary=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.License; v != nil {
		builder.WriteString("license=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Blurhash; v != nil {
		builder.WriteString("blurhash=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("order=")
	builder.WriteString(fmt.Sprintf("%v", _m.Order))
	builder.WriteString(", ")
	if v := _m.Width; v != nil {
		builder.WriteString("width=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Height; v != nil {
		builder.WriteString("height=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("local_user=")
	builder.WriteString(fmt.Sprintf("%v", _m.LocalUser))
	builder.WriteString(", ")
	builder.WriteString("is_cached=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCached))
	builder.WriteString(", ")
	builder.WriteString("is_comment=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsComment))
	builder.WriteString(", ")
	if v := _m.Metadata; v != nil {
		builder.WriteString("metadata=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(_m.Version)
	builder.WriteString(", ")
	builder.WriteString("skip_optimize=")
	builder.WriteString(fmt.Sprintf("%v", _m.SkipOptimize))
	builder.WriteString(", ")
	if v := _m.ProcessedAt; v != nil {
		builder.WriteString("processed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ThumbnailGenerated; v != nil {
		builder.WriteString("thumbnail_generated=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// GroupMediaSlice is a parsable slice of GroupMedia.
type GroupMediaSlice []*GroupMedia
