// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/job"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobCreate is the builder for creating a Job entity.
type JobCreate struct {
	config
	mutation *JobMutation
	hooks    []Hook
}

// SetQueue sets the "queue" field.
func (_c *JobCreate) SetQueue(v string) *JobCreate {
	_c.mutation.SetQueue(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *JobCreate) SetPayload(v string) *JobCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetAttempts sets the "attempts" field.
func (_c *JobCreate) SetAttempts(v uint) *JobCreate {
	_c.mutation.SetAttempts(v)
	return _c
}

// SetReservedAt sets the "reserved_at" field.
func (_c *JobCreate) SetReservedAt(v uint) *JobCreate {
	_c.mutation.SetReservedAt(v)
	return _c
}

// SetNillableReservedAt sets the "reserved_at" field if the given value is not nil.
func (_c *JobCreate) SetNillableReservedAt(v *uint) *JobCreate {
	if v != nil {
		_c.SetReservedAt(*v)
	}
	return _c
}

// SetAvailableAt sets the "available_at" field.
func (_c *JobCreate) SetAvailableAt(v uint) *JobCreate {
	_c.mutation.SetAvailableAt(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *JobCreate) SetCreatedAt(v uint) *JobCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetID sets the "id" field.
func (_c *JobCreate) SetID(v uint64) *JobCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the JobMutation object of the builder.
func (_c *JobCreate) Mutation() *JobMutation {
	return _c.mutation
}

// Save creates the Job in the database.
func (_c *JobCreate) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *JobCreate) SaveX(ctx context.Context) *Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *JobCreate) check() error {
	if _, ok := _c.mutation.Queue(); !ok {
		return &ValidationError{Name: "queue", err: errors.New(`ent: missing required field "Job.queue"`)}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "Job.payload"`)}
	}
	if _, ok := _c.mutation.Attempts(); !ok {
		return &ValidationError{Name: "attempts", err: errors.New(`ent: missing required field "Job.attempts"`)}
	}
	if _, ok := _c.mutation.AvailableAt(); !ok {
		return &ValidationError{Name: "available_at", err: errors.New(`ent: missing required field "Job.available_at"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Job.created_at"`)}
	}
	return nil
}

func (_c *JobCreate) sqlSave(ctx context.Context) (*Job, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *JobCreate) createSpec() (*Job, *sqlgraph.CreateSpec) {
	var (
		_node = &Job{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(job.Table, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Queue(); ok {
		_spec.SetField(job.FieldQueue, field.TypeString, value)
		_node.Queue = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeString, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeUint, value)
		_node.Attempts = value
	}
	if value, ok := _c.mutation.ReservedAt(); ok {
		_spec.SetField(job.FieldReservedAt, field.TypeUint, value)
		_node.ReservedAt = &value
	}
	if value, ok := _c.mutation.AvailableAt(); ok {
		_spec.SetField(job.FieldAvailableAt, field.TypeUint, value)
		_node.AvailableAt = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeUint, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// JobCreateBulk is the builder for creating many Job entities in bulk.
type JobCreateBulk struct {
	config
	err      error
	builders []*JobCreate
}

// Save creates the Job entities in the database.
func (_c *JobCreateBulk) Save(ctx context.Context) ([]*Job, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Job, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*JobMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *JobCreateBulk) SaveX(ctx context.Context) []*Job {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *JobCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *JobCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
