// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/job"
	"glintfed/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JobUpdate is the builder for updating Job entities.
type JobUpdate struct {
	config
	hooks    []Hook
	mutation *JobMutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdate) Where(ps ...predicate.Job) *JobUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetQueue sets the "queue" field.
func (_u *JobUpdate) SetQueue(v string) *JobUpdate {
	_u.mutation.SetQueue(v)
	return _u
}

// SetNillableQueue sets the "queue" field if the given value is not nil.
func (_u *JobUpdate) SetNillableQueue(v *string) *JobUpdate {
	if v != nil {
		_u.SetQueue(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *JobUpdate) SetPayload(v string) *JobUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *JobUpdate) SetNillablePayload(v *string) *JobUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *JobUpdate) SetAttempts(v uint) *JobUpdate {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *JobUpdate) SetNillableAttempts(v *uint) *JobUpdate {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *JobUpdate) AddAttempts(v int) *JobUpdate {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetReservedAt sets the "reserved_at" field.
func (_u *JobUpdate) SetReservedAt(v uint) *JobUpdate {
	_u.mutation.ResetReservedAt()
	_u.mutation.SetReservedAt(v)
	return _u
}

// SetNillableReservedAt sets the "reserved_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableReservedAt(v *uint) *JobUpdate {
	if v != nil {
		_u.SetReservedAt(*v)
	}
	return _u
}

// AddReservedAt adds value to the "reserved_at" field.
func (_u *JobUpdate) AddReservedAt(v int) *JobUpdate {
	_u.mutation.AddReservedAt(v)
	return _u
}

// ClearReservedAt clears the value of the "reserved_at" field.
func (_u *JobUpdate) ClearReservedAt() *JobUpdate {
	_u.mutation.ClearReservedAt()
	return _u
}

// SetAvailableAt sets the "available_at" field.
func (_u *JobUpdate) SetAvailableAt(v uint) *JobUpdate {
	_u.mutation.ResetAvailableAt()
	_u.mutation.SetAvailableAt(v)
	return _u
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableAvailableAt(v *uint) *JobUpdate {
	if v != nil {
		_u.SetAvailableAt(*v)
	}
	return _u
}

// AddAvailableAt adds value to the "available_at" field.
func (_u *JobUpdate) AddAvailableAt(v int) *JobUpdate {
	_u.mutation.AddAvailableAt(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *JobUpdate) SetCreatedAt(v uint) *JobUpdate {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *JobUpdate) SetNillableCreatedAt(v *uint) *JobUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *JobUpdate) AddCreatedAt(v int) *JobUpdate {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdate) Mutation() *JobMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *JobUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *JobUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *JobUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Queue(); ok {
		_spec.SetField(job.FieldQueue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(job.FieldAttempts, field.TypeUint, value)
	}
	if value, ok := _u.mutation.ReservedAt(); ok {
		_spec.SetField(job.FieldReservedAt, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedReservedAt(); ok {
		_spec.AddField(job.FieldReservedAt, field.TypeUint, value)
	}
	if _u.mutation.ReservedAtCleared() {
		_spec.ClearField(job.FieldReservedAt, field.TypeUint)
	}
	if value, ok := _u.mutation.AvailableAt(); ok {
		_spec.SetField(job.FieldAvailableAt, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedAvailableAt(); ok {
		_spec.AddField(job.FieldAvailableAt, field.TypeUint, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(job.FieldCreatedAt, field.TypeUint, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// JobUpdateOne is the builder for updating a single Job entity.
type JobUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JobMutation
}

// SetQueue sets the "queue" field.
func (_u *JobUpdateOne) SetQueue(v string) *JobUpdateOne {
	_u.mutation.SetQueue(v)
	return _u
}

// SetNillableQueue sets the "queue" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableQueue(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetQueue(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *JobUpdateOne) SetPayload(v string) *JobUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillablePayload(v *string) *JobUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetAttempts sets the "attempts" field.
func (_u *JobUpdateOne) SetAttempts(v uint) *JobUpdateOne {
	_u.mutation.ResetAttempts()
	_u.mutation.SetAttempts(v)
	return _u
}

// SetNillableAttempts sets the "attempts" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableAttempts(v *uint) *JobUpdateOne {
	if v != nil {
		_u.SetAttempts(*v)
	}
	return _u
}

// AddAttempts adds value to the "attempts" field.
func (_u *JobUpdateOne) AddAttempts(v int) *JobUpdateOne {
	_u.mutation.AddAttempts(v)
	return _u
}

// SetReservedAt sets the "reserved_at" field.
func (_u *JobUpdateOne) SetReservedAt(v uint) *JobUpdateOne {
	_u.mutation.ResetReservedAt()
	_u.mutation.SetReservedAt(v)
	return _u
}

// SetNillableReservedAt sets the "reserved_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableReservedAt(v *uint) *JobUpdateOne {
	if v != nil {
		_u.SetReservedAt(*v)
	}
	return _u
}

// AddReservedAt adds value to the "reserved_at" field.
func (_u *JobUpdateOne) AddReservedAt(v int) *JobUpdateOne {
	_u.mutation.AddReservedAt(v)
	return _u
}

// ClearReservedAt clears the value of the "reserved_at" field.
func (_u *JobUpdateOne) ClearReservedAt() *JobUpdateOne {
	_u.mutation.ClearReservedAt()
	return _u
}

// SetAvailableAt sets the "available_at" field.
func (_u *JobUpdateOne) SetAvailableAt(v uint) *JobUpdateOne {
	_u.mutation.ResetAvailableAt()
	_u.mutation.SetAvailableAt(v)
	return _u
}

// SetNillableAvailableAt sets the "available_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableAvailableAt(v *uint) *JobUpdateOne {
	if v != nil {
		_u.SetAvailableAt(*v)
	}
	return _u
}

// AddAvailableAt adds value to the "available_at" field.
func (_u *JobUpdateOne) AddAvailableAt(v int) *JobUpdateOne {
	_u.mutation.AddAvailableAt(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *JobUpdateOne) SetCreatedAt(v uint) *JobUpdateOne {
	_u.mutation.ResetCreatedAt()
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *JobUpdateOne) SetNillableCreatedAt(v *uint) *JobUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// AddCreatedAt adds value to the "created_at" field.
func (_u *JobUpdateOne) AddCreatedAt(v int) *JobUpdateOne {
	_u.mutation.AddCreatedAt(v)
	return _u
}

// Mutation returns the JobMutation object of the builder.
func (_u *JobUpdateOne) Mutation() *JobMutation {
	return _u.mutation
}

// Where appends a list predicates to the JobUpdate builder.
func (_u *JobUpdateOne) Where(ps ...predicate.Job) *JobUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *JobUpdateOne) Select(field string, fields ...string) *JobUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Job entity.
func (_u *JobUpdateOne) Save(ctx context.Context) (*Job, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *JobUpdateOne) SaveX(ctx context.Context) *Job {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *JobUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *JobUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *JobUpdateOne) sqlSave(ctx context.Context) (_node *Job, err error) {
	_spec := sqlgraph.NewUpdateSpec(job.Table, job.Columns, sqlgraph.NewFieldSpec(job.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Job.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, job.FieldID)
		for _, f := range fields {
			if !job.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != job.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Queue(); ok {
		_spec.SetField(job.FieldQueue, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(job.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.Attempts(); ok {
		_spec.SetField(job.FieldAttempts, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedAttempts(); ok {
		_spec.AddField(job.FieldAttempts, field.TypeUint, value)
	}
	if value, ok := _u.mutation.ReservedAt(); ok {
		_spec.SetField(job.FieldReservedAt, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedReservedAt(); ok {
		_spec.AddField(job.FieldReservedAt, field.TypeUint, value)
	}
	if _u.mutation.ReservedAtCleared() {
		_spec.ClearField(job.FieldReservedAt, field.TypeUint)
	}
	if value, ok := _u.mutation.AvailableAt(); ok {
		_spec.SetField(job.FieldAvailableAt, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedAvailableAt(); ok {
		_spec.AddField(job.FieldAvailableAt, field.TypeUint, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(job.FieldCreatedAt, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedCreatedAt(); ok {
		_spec.AddField(job.FieldCreatedAt, field.TypeUint, value)
	}
	_node = &Job{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{job.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
