// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"glintfed/ent/jobbatch"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// JobBatch is the model entity for the JobBatch schema.
type JobBatch struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// TotalJobs holds the value of the "total_jobs" field.
	TotalJobs int `json:"total_jobs,omitempty"`
	// PendingJobs holds the value of the "pending_jobs" field.
	PendingJobs int `json:"pending_jobs,omitempty"`
	// FailedJobs holds the value of the "failed_jobs" field.
	FailedJobs int `json:"failed_jobs,omitempty"`
	// FailedJobIds holds the value of the "failed_job_ids" field.
	FailedJobIds string `json:"failed_job_ids,omitempty"`
	// Options holds the value of the "options" field.
	Options *string `json:"options,omitempty"`
	// CancelledAt holds the value of the "cancelled_at" field.
	CancelledAt *int `json:"cancelled_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int `json:"created_at,omitempty"`
	// FinishedAt holds the value of the "finished_at" field.
	FinishedAt   *int `json:"finished_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*JobBatch) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case jobbatch.FieldTotalJobs, jobbatch.FieldPendingJobs, jobbatch.FieldFailedJobs, jobbatch.FieldCancelledAt, jobbatch.FieldCreatedAt, jobbatch.FieldFinishedAt:
			values[i] = new(sql.NullInt64)
		case jobbatch.FieldID, jobbatch.FieldName, jobbatch.FieldFailedJobIds, jobbatch.FieldOptions:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the JobBatch fields.
func (_m *JobBatch) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case jobbatch.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case jobbatch.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case jobbatch.FieldTotalJobs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_jobs", values[i])
			} else if value.Valid {
				_m.TotalJobs = int(value.Int64)
			}
		case jobbatch.FieldPendingJobs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pending_jobs", values[i])
			} else if value.Valid {
				_m.PendingJobs = int(value.Int64)
			}
		case jobbatch.FieldFailedJobs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field failed_jobs", values[i])
			} else if value.Valid {
				_m.FailedJobs = int(value.Int64)
			}
		case jobbatch.FieldFailedJobIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field failed_job_ids", values[i])
			} else if value.Valid {
				_m.FailedJobIds = value.String
			}
		case jobbatch.FieldOptions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field options", values[i])
			} else if value.Valid {
				_m.Options = new(string)
				*_m.Options = value.String
			}
		case jobbatch.FieldCancelledAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cancelled_at", values[i])
			} else if value.Valid {
				_m.CancelledAt = new(int)
				*_m.CancelledAt = int(value.Int64)
			}
		case jobbatch.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = int(value.Int64)
			}
		case jobbatch.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(int)
				*_m.FinishedAt = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the JobBatch.
// This includes values selected through modifiers, order, etc.
func (_m *JobBatch) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this JobBatch.
// Note that you need to call JobBatch.Unwrap() before calling this method if this JobBatch
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *JobBatch) Update() *JobBatchUpdateOne {
	return NewJobBatchClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the JobBatch entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *JobBatch) Unwrap() *JobBatch {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: JobBatch is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *JobBatch) String() string {
	var builder strings.Builder
	builder.WriteString("JobBatch(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("total_jobs=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalJobs))
	builder.WriteString(", ")
	builder.WriteString("pending_jobs=")
	builder.WriteString(fmt.Sprintf("%v", _m.PendingJobs))
	builder.WriteString(", ")
	builder.WriteString("failed_jobs=")
	builder.WriteString(fmt.Sprintf("%v", _m.FailedJobs))
	builder.WriteString(", ")
	builder.WriteString("failed_job_ids=")
	builder.WriteString(_m.FailedJobIds)
	builder.WriteString(", ")
	if v := _m.Options; v != nil {
		builder.WriteString("options=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CancelledAt; v != nil {
		builder.WriteString("cancelled_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", _m.CreatedAt))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// JobBatches is a parsable slice of JobBatch.
type JobBatches []*JobBatch
