// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/like"
	"glintfed/ent/predicate"
	"glintfed/ent/profile"
	"glintfed/ent/status"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LikeUpdate is the builder for updating Like entities.
type LikeUpdate struct {
	config
	hooks    []Hook
	mutation *LikeMutation
}

// Where appends a list predicates to the LikeUpdate builder.
func (_u *LikeUpdate) Where(ps ...predicate.Like) *LikeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *LikeUpdate) SetProfileID(v uint64) *LikeUpdate {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *LikeUpdate) SetNillableProfileID(v *uint64) *LikeUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetStatusID sets the "status_id" field.
func (_u *LikeUpdate) SetStatusID(v uint64) *LikeUpdate {
	_u.mutation.SetStatusID(v)
	return _u
}

// SetNillableStatusID sets the "status_id" field if the given value is not nil.
func (_u *LikeUpdate) SetNillableStatusID(v *uint64) *LikeUpdate {
	if v != nil {
		_u.SetStatusID(*v)
	}
	return _u
}

// SetStatusProfileID sets the "status_profile_id" field.
func (_u *LikeUpdate) SetStatusProfileID(v uint64) *LikeUpdate {
	_u.mutation.ResetStatusProfileID()
	_u.mutation.SetStatusProfileID(v)
	return _u
}

// SetNillableStatusProfileID sets the "status_profile_id" field if the given value is not nil.
func (_u *LikeUpdate) SetNillableStatusProfileID(v *uint64) *LikeUpdate {
	if v != nil {
		_u.SetStatusProfileID(*v)
	}
	return _u
}

// AddStatusProfileID adds value to the "status_profile_id" field.
func (_u *LikeUpdate) AddStatusProfileID(v int64) *LikeUpdate {
	_u.mutation.AddStatusProfileID(v)
	return _u
}

// ClearStatusProfileID clears the value of the "status_profile_id" field.
func (_u *LikeUpdate) ClearStatusProfileID() *LikeUpdate {
	_u.mutation.ClearStatusProfileID()
	return _u
}

// SetIsComment sets the "is_comment" field.
func (_u *LikeUpdate) SetIsComment(v bool) *LikeUpdate {
	_u.mutation.SetIsComment(v)
	return _u
}

// SetNillableIsComment sets the "is_comment" field if the given value is not nil.
func (_u *LikeUpdate) SetNillableIsComment(v *bool) *LikeUpdate {
	if v != nil {
		_u.SetIsComment(*v)
	}
	return _u
}

// ClearIsComment clears the value of the "is_comment" field.
func (_u *LikeUpdate) ClearIsComment() *LikeUpdate {
	_u.mutation.ClearIsComment()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LikeUpdate) SetCreatedAt(v time.Time) *LikeUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LikeUpdate) SetNillableCreatedAt(v *time.Time) *LikeUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *LikeUpdate) ClearCreatedAt() *LikeUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LikeUpdate) SetUpdatedAt(v time.Time) *LikeUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *LikeUpdate) SetNillableUpdatedAt(v *time.Time) *LikeUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *LikeUpdate) ClearUpdatedAt() *LikeUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LikeUpdate) SetDeletedAt(v time.Time) *LikeUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LikeUpdate) SetNillableDeletedAt(v *time.Time) *LikeUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LikeUpdate) ClearDeletedAt() *LikeUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetActorID sets the "actor" edge to the Profile entity by ID.
func (_u *LikeUpdate) SetActorID(id uint64) *LikeUpdate {
	_u.mutation.SetActorID(id)
	return _u
}

// SetActor sets the "actor" edge to the Profile entity.
func (_u *LikeUpdate) SetActor(v *Profile) *LikeUpdate {
	return _u.SetActorID(v.ID)
}

// SetStatus sets the "status" edge to the Status entity.
func (_u *LikeUpdate) SetStatus(v *Status) *LikeUpdate {
	return _u.SetStatusID(v.ID)
}

// Mutation returns the LikeMutation object of the builder.
func (_u *LikeUpdate) Mutation() *LikeMutation {
	return _u.mutation
}

// ClearActor clears the "actor" edge to the Profile entity.
func (_u *LikeUpdate) ClearActor() *LikeUpdate {
	_u.mutation.ClearActor()
	return _u
}

// ClearStatus clears the "status" edge to the Status entity.
func (_u *LikeUpdate) ClearStatus() *LikeUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LikeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LikeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LikeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LikeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LikeUpdate) check() error {
	if _u.mutation.ActorCleared() && len(_u.mutation.ActorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Like.actor"`)
	}
	if _u.mutation.StatusCleared() && len(_u.mutation.StatusIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Like.status"`)
	}
	return nil
}

func (_u *LikeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(like.Table, like.Columns, sqlgraph.NewFieldSpec(like.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StatusProfileID(); ok {
		_spec.SetField(like.FieldStatusProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedStatusProfileID(); ok {
		_spec.AddField(like.FieldStatusProfileID, field.TypeUint64, value)
	}
	if _u.mutation.StatusProfileIDCleared() {
		_spec.ClearField(like.FieldStatusProfileID, field.TypeUint64)
	}
	if value, ok := _u.mutation.IsComment(); ok {
		_spec.SetField(like.FieldIsComment, field.TypeBool, value)
	}
	if _u.mutation.IsCommentCleared() {
		_spec.ClearField(like.FieldIsComment, field.TypeBool)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(like.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(like.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(like.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(like.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(like.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(like.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ActorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   like.ActorTable,
			Columns: []string{like.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   like.ActorTable,
			Columns: []string{like.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   like.StatusTable,
			Columns: []string{like.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   like.StatusTable,
			Columns: []string{like.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{like.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LikeUpdateOne is the builder for updating a single Like entity.
type LikeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LikeMutation
}

// SetProfileID sets the "profile_id" field.
func (_u *LikeUpdateOne) SetProfileID(v uint64) *LikeUpdateOne {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *LikeUpdateOne) SetNillableProfileID(v *uint64) *LikeUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// SetStatusID sets the "status_id" field.
func (_u *LikeUpdateOne) SetStatusID(v uint64) *LikeUpdateOne {
	_u.mutation.SetStatusID(v)
	return _u
}

// SetNillableStatusID sets the "status_id" field if the given value is not nil.
func (_u *LikeUpdateOne) SetNillableStatusID(v *uint64) *LikeUpdateOne {
	if v != nil {
		_u.SetStatusID(*v)
	}
	return _u
}

// SetStatusProfileID sets the "status_profile_id" field.
func (_u *LikeUpdateOne) SetStatusProfileID(v uint64) *LikeUpdateOne {
	_u.mutation.ResetStatusProfileID()
	_u.mutation.SetStatusProfileID(v)
	return _u
}

// SetNillableStatusProfileID sets the "status_profile_id" field if the given value is not nil.
func (_u *LikeUpdateOne) SetNillableStatusProfileID(v *uint64) *LikeUpdateOne {
	if v != nil {
		_u.SetStatusProfileID(*v)
	}
	return _u
}

// AddStatusProfileID adds value to the "status_profile_id" field.
func (_u *LikeUpdateOne) AddStatusProfileID(v int64) *LikeUpdateOne {
	_u.mutation.AddStatusProfileID(v)
	return _u
}

// ClearStatusProfileID clears the value of the "status_profile_id" field.
func (_u *LikeUpdateOne) ClearStatusProfileID() *LikeUpdateOne {
	_u.mutation.ClearStatusProfileID()
	return _u
}

// SetIsComment sets the "is_comment" field.
func (_u *LikeUpdateOne) SetIsComment(v bool) *LikeUpdateOne {
	_u.mutation.SetIsComment(v)
	return _u
}

// SetNillableIsComment sets the "is_comment" field if the given value is not nil.
func (_u *LikeUpdateOne) SetNillableIsComment(v *bool) *LikeUpdateOne {
	if v != nil {
		_u.SetIsComment(*v)
	}
	return _u
}

// ClearIsComment clears the value of the "is_comment" field.
func (_u *LikeUpdateOne) ClearIsComment() *LikeUpdateOne {
	_u.mutation.ClearIsComment()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LikeUpdateOne) SetCreatedAt(v time.Time) *LikeUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LikeUpdateOne) SetNillableCreatedAt(v *time.Time) *LikeUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *LikeUpdateOne) ClearCreatedAt() *LikeUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *LikeUpdateOne) SetUpdatedAt(v time.Time) *LikeUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *LikeUpdateOne) SetNillableUpdatedAt(v *time.Time) *LikeUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *LikeUpdateOne) ClearUpdatedAt() *LikeUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *LikeUpdateOne) SetDeletedAt(v time.Time) *LikeUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *LikeUpdateOne) SetNillableDeletedAt(v *time.Time) *LikeUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *LikeUpdateOne) ClearDeletedAt() *LikeUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetActorID sets the "actor" edge to the Profile entity by ID.
func (_u *LikeUpdateOne) SetActorID(id uint64) *LikeUpdateOne {
	_u.mutation.SetActorID(id)
	return _u
}

// SetActor sets the "actor" edge to the Profile entity.
func (_u *LikeUpdateOne) SetActor(v *Profile) *LikeUpdateOne {
	return _u.SetActorID(v.ID)
}

// SetStatus sets the "status" edge to the Status entity.
func (_u *LikeUpdateOne) SetStatus(v *Status) *LikeUpdateOne {
	return _u.SetStatusID(v.ID)
}

// Mutation returns the LikeMutation object of the builder.
func (_u *LikeUpdateOne) Mutation() *LikeMutation {
	return _u.mutation
}

// ClearActor clears the "actor" edge to the Profile entity.
func (_u *LikeUpdateOne) ClearActor() *LikeUpdateOne {
	_u.mutation.ClearActor()
	return _u
}

// ClearStatus clears the "status" edge to the Status entity.
func (_u *LikeUpdateOne) ClearStatus() *LikeUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// Where appends a list predicates to the LikeUpdate builder.
func (_u *LikeUpdateOne) Where(ps ...predicate.Like) *LikeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LikeUpdateOne) Select(field string, fields ...string) *LikeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Like entity.
func (_u *LikeUpdateOne) Save(ctx context.Context) (*Like, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LikeUpdateOne) SaveX(ctx context.Context) *Like {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LikeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LikeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LikeUpdateOne) check() error {
	if _u.mutation.ActorCleared() && len(_u.mutation.ActorIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Like.actor"`)
	}
	if _u.mutation.StatusCleared() && len(_u.mutation.StatusIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Like.status"`)
	}
	return nil
}

func (_u *LikeUpdateOne) sqlSave(ctx context.Context) (_node *Like, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(like.Table, like.Columns, sqlgraph.NewFieldSpec(like.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Like.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, like.FieldID)
		for _, f := range fields {
			if !like.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != like.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StatusProfileID(); ok {
		_spec.SetField(like.FieldStatusProfileID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedStatusProfileID(); ok {
		_spec.AddField(like.FieldStatusProfileID, field.TypeUint64, value)
	}
	if _u.mutation.StatusProfileIDCleared() {
		_spec.ClearField(like.FieldStatusProfileID, field.TypeUint64)
	}
	if value, ok := _u.mutation.IsComment(); ok {
		_spec.SetField(like.FieldIsComment, field.TypeBool, value)
	}
	if _u.mutation.IsCommentCleared() {
		_spec.ClearField(like.FieldIsComment, field.TypeBool)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(like.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(like.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(like.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(like.FieldUpdatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(like.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(like.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.ActorCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   like.ActorTable,
			Columns: []string{like.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ActorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   like.ActorTable,
			Columns: []string{like.ActorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.StatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   like.StatusTable,
			Columns: []string{like.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   like.StatusTable,
			Columns: []string{like.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Like{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{like.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
