// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/migration"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// MigrationCreate is the builder for creating a Migration entity.
type MigrationCreate struct {
	config
	mutation *MigrationMutation
	hooks    []Hook
}

// SetMigration sets the "migration" field.
func (_c *MigrationCreate) SetMigration(v string) *MigrationCreate {
	_c.mutation.SetMigration(v)
	return _c
}

// SetBatch sets the "batch" field.
func (_c *MigrationCreate) SetBatch(v int) *MigrationCreate {
	_c.mutation.SetBatch(v)
	return _c
}

// SetID sets the "id" field.
func (_c *MigrationCreate) SetID(v uint) *MigrationCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the MigrationMutation object of the builder.
func (_c *MigrationCreate) Mutation() *MigrationMutation {
	return _c.mutation
}

// Save creates the Migration in the database.
func (_c *MigrationCreate) Save(ctx context.Context) (*Migration, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *MigrationCreate) SaveX(ctx context.Context) *Migration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MigrationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MigrationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *MigrationCreate) check() error {
	if _, ok := _c.mutation.Migration(); !ok {
		return &ValidationError{Name: "migration", err: errors.New(`ent: missing required field "Migration.migration"`)}
	}
	if _, ok := _c.mutation.Batch(); !ok {
		return &ValidationError{Name: "batch", err: errors.New(`ent: missing required field "Migration.batch"`)}
	}
	return nil
}

func (_c *MigrationCreate) sqlSave(ctx context.Context) (*Migration, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *MigrationCreate) createSpec() (*Migration, *sqlgraph.CreateSpec) {
	var (
		_node = &Migration{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(migration.Table, sqlgraph.NewFieldSpec(migration.FieldID, field.TypeUint))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Migration(); ok {
		_spec.SetField(migration.FieldMigration, field.TypeString, value)
		_node.Migration = value
	}
	if value, ok := _c.mutation.Batch(); ok {
		_spec.SetField(migration.FieldBatch, field.TypeInt, value)
		_node.Batch = value
	}
	return _node, _spec
}

// MigrationCreateBulk is the builder for creating many Migration entities in bulk.
type MigrationCreateBulk struct {
	config
	err      error
	builders []*MigrationCreate
}

// Save creates the Migration entities in the database.
func (_c *MigrationCreateBulk) Save(ctx context.Context) ([]*Migration, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Migration, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MigrationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *MigrationCreateBulk) SaveX(ctx context.Context) []*Migration {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *MigrationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *MigrationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
