// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"glintfed/ent/modlog"
	"glintfed/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ModLog is the model entity for the ModLog schema.
type ModLog struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uint64 `json:"user_id,omitempty"`
	// UserUsername holds the value of the "user_username" field.
	UserUsername *string `json:"user_username,omitempty"`
	// ObjectUID holds the value of the "object_uid" field.
	ObjectUID *uint64 `json:"object_uid,omitempty"`
	// ObjectID holds the value of the "object_id" field.
	ObjectID *uint64 `json:"object_id,omitempty"`
	// ObjectType holds the value of the "object_type" field.
	ObjectType *string `json:"object_type,omitempty"`
	// Action holds the value of the "action" field.
	Action *string `json:"action,omitempty"`
	// Message holds the value of the "message" field.
	Message *string `json:"message,omitempty"`
	// Metadata holds the value of the "metadata" field.
	Metadata *string `json:"metadata,omitempty"`
	// AccessLevel holds the value of the "access_level" field.
	AccessLevel *string `json:"access_level,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModLogQuery when eager-loading is set.
	Edges        ModLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModLogEdges holds the relations/edges for other nodes in the graph.
type ModLogEdges struct {
	// Admin holds the value of the admin edge.
	Admin *User `json:"admin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AdminOrErr returns the Admin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModLogEdges) AdminOrErr() (*User, error) {
	if e.Admin != nil {
		return e.Admin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "admin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case modlog.FieldID, modlog.FieldUserID, modlog.FieldObjectUID, modlog.FieldObjectID:
			values[i] = new(sql.NullInt64)
		case modlog.FieldUserUsername, modlog.FieldObjectType, modlog.FieldAction, modlog.FieldMessage, modlog.FieldMetadata, modlog.FieldAccessLevel:
			values[i] = new(sql.NullString)
		case modlog.FieldCreatedAt, modlog.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModLog fields.
func (_m *ModLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case modlog.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case modlog.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = uint64(value.Int64)
			}
		case modlog.FieldUserUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field user_username", values[i])
			} else if value.Valid {
				_m.UserUsername = new(string)
				*_m.UserUsername = value.String
			}
		case modlog.FieldObjectUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field object_uid", values[i])
			} else if value.Valid {
				_m.ObjectUID = new(uint64)
				*_m.ObjectUID = uint64(value.Int64)
			}
		case modlog.FieldObjectID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field object_id", values[i])
			} else if value.Valid {
				_m.ObjectID = new(uint64)
				*_m.ObjectID = uint64(value.Int64)
			}
		case modlog.FieldObjectType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field object_type", values[i])
			} else if value.Valid {
				_m.ObjectType = new(string)
				*_m.ObjectType = value.String
			}
		case modlog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = new(string)
				*_m.Action = value.String
			}
		case modlog.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = new(string)
				*_m.Message = value.String
			}
		case modlog.FieldMetadata:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field metadata", values[i])
			} else if value.Valid {
				_m.Metadata = new(string)
				*_m.Metadata = value.String
			}
		case modlog.FieldAccessLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_level", values[i])
			} else if value.Valid {
				_m.AccessLevel = new(string)
				*_m.AccessLevel = value.String
			}
		case modlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case modlog.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModLog.
// This includes values selected through modifiers, order, etc.
func (_m *ModLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAdmin queries the "admin" edge of the ModLog entity.
func (_m *ModLog) QueryAdmin() *UserQuery {
	return NewModLogClient(_m.config).QueryAdmin(_m)
}

// Update returns a builder for updating this ModLog.
// Note that you need to call ModLog.Unwrap() before calling this method if this ModLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModLog) Update() *ModLogUpdateOne {
	return NewModLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModLog) Unwrap() *ModLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModLog) String() string {
	var builder strings.Builder
	builder.WriteString("ModLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	if v := _m.UserUsername; v != nil {
		builder.WriteString("user_username=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ObjectUID; v != nil {
		builder.WriteString("object_uid=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ObjectID; v != nil {
		builder.WriteString("object_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ObjectType; v != nil {
		builder.WriteString("object_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Action; v != nil {
		builder.WriteString("action=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Message; v != nil {
		builder.WriteString("message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Metadata; v != nil {
		builder.WriteString("metadata=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AccessLevel; v != nil {
		builder.WriteString("access_level=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModLogs is a parsable slice of ModLog.
type ModLogs []*ModLog
