// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"glintfed/ent/notification"
	"glintfed/ent/profile"
	"glintfed/ent/status"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Notification is the model entity for the Notification schema.
type Notification struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID uint64 `json:"profile_id,omitempty"`
	// ActorID holds the value of the "actor_id" field.
	ActorID *uint64 `json:"actor_id,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID *uint64 `json:"item_id,omitempty"`
	// ItemType holds the value of the "item_type" field.
	ItemType *string `json:"item_type,omitempty"`
	// Action holds the value of the "action" field.
	Action *string `json:"action,omitempty"`
	// ReadAt holds the value of the "read_at" field.
	ReadAt *time.Time `json:"read_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the NotificationQuery when eager-loading is set.
	Edges        NotificationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// NotificationEdges holds the relations/edges for other nodes in the graph.
type NotificationEdges struct {
	// Actor holds the value of the actor edge.
	Actor *Profile `json:"actor,omitempty"`
	// Profile holds the value of the profile edge.
	Profile *Profile `json:"profile,omitempty"`
	// Status holds the value of the status edge.
	Status *Status `json:"status,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// ActorOrErr returns the Actor value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationEdges) ActorOrErr() (*Profile, error) {
	if e.Actor != nil {
		return e.Actor, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: profile.Label}
	}
	return nil, &NotLoadedError{edge: "actor"}
}

// ProfileOrErr returns the Profile value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationEdges) ProfileOrErr() (*Profile, error) {
	if e.Profile != nil {
		return e.Profile, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: profile.Label}
	}
	return nil, &NotLoadedError{edge: "profile"}
}

// StatusOrErr returns the Status value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e NotificationEdges) StatusOrErr() (*Status, error) {
	if e.Status != nil {
		return e.Status, nil
	} else if e.loadedTypes[2] {
		return nil, &NotFoundError{label: status.Label}
	}
	return nil, &NotLoadedError{edge: "status"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Notification) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case notification.FieldID, notification.FieldProfileID, notification.FieldActorID, notification.FieldItemID:
			values[i] = new(sql.NullInt64)
		case notification.FieldItemType, notification.FieldAction:
			values[i] = new(sql.NullString)
		case notification.FieldReadAt, notification.FieldCreatedAt, notification.FieldUpdatedAt, notification.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Notification fields.
func (_m *Notification) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case notification.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case notification.FieldProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = uint64(value.Int64)
			}
		case notification.FieldActorID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field actor_id", values[i])
			} else if value.Valid {
				_m.ActorID = new(uint64)
				*_m.ActorID = uint64(value.Int64)
			}
		case notification.FieldItemID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				_m.ItemID = new(uint64)
				*_m.ItemID = uint64(value.Int64)
			}
		case notification.FieldItemType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_type", values[i])
			} else if value.Valid {
				_m.ItemType = new(string)
				*_m.ItemType = value.String
			}
		case notification.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = new(string)
				*_m.Action = value.String
			}
		case notification.FieldReadAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field read_at", values[i])
			} else if value.Valid {
				_m.ReadAt = new(time.Time)
				*_m.ReadAt = value.Time
			}
		case notification.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case notification.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case notification.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Notification.
// This includes values selected through modifiers, order, etc.
func (_m *Notification) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryActor queries the "actor" edge of the Notification entity.
func (_m *Notification) QueryActor() *ProfileQuery {
	return NewNotificationClient(_m.config).QueryActor(_m)
}

// QueryProfile queries the "profile" edge of the Notification entity.
func (_m *Notification) QueryProfile() *ProfileQuery {
	return NewNotificationClient(_m.config).QueryProfile(_m)
}

// QueryStatus queries the "status" edge of the Notification entity.
func (_m *Notification) QueryStatus() *StatusQuery {
	return NewNotificationClient(_m.config).QueryStatus(_m)
}

// Update returns a builder for updating this Notification.
// Note that you need to call Notification.Unwrap() before calling this method if this Notification
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Notification) Update() *NotificationUpdateOne {
	return NewNotificationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Notification entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Notification) Unwrap() *Notification {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Notification is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Notification) String() string {
	var builder strings.Builder
	builder.WriteString("Notification(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProfileID))
	builder.WriteString(", ")
	if v := _m.ActorID; v != nil {
		builder.WriteString("actor_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ItemID; v != nil {
		builder.WriteString("item_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ItemType; v != nil {
		builder.WriteString("item_type=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Action; v != nil {
		builder.WriteString("action=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ReadAt; v != nil {
		builder.WriteString("read_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Notifications is a parsable slice of Notification.
type Notifications []*Notification
