// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"glintfed/ent/oauthauthcode"
	"glintfed/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// OauthAuthCodeDelete is the builder for deleting a OauthAuthCode entity.
type OauthAuthCodeDelete struct {
	config
	hooks    []Hook
	mutation *OauthAuthCodeMutation
}

// Where appends a list predicates to the OauthAuthCodeDelete builder.
func (_d *OauthAuthCodeDelete) Where(ps ...predicate.OauthAuthCode) *OauthAuthCodeDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *OauthAuthCodeDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OauthAuthCodeDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *OauthAuthCodeDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(oauthauthcode.Table, sqlgraph.NewFieldSpec(oauthauthcode.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// OauthAuthCodeDeleteOne is the builder for deleting a single OauthAuthCode entity.
type OauthAuthCodeDeleteOne struct {
	_d *OauthAuthCodeDelete
}

// Where appends a list predicates to the OauthAuthCodeDelete builder.
func (_d *OauthAuthCodeDeleteOne) Where(ps ...predicate.OauthAuthCode) *OauthAuthCodeDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *OauthAuthCodeDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{oauthauthcode.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *OauthAuthCodeDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
