// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/predicate"
	"glintfed/ent/pulsevalue"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PulseValueUpdate is the builder for updating PulseValue entities.
type PulseValueUpdate struct {
	config
	hooks    []Hook
	mutation *PulseValueMutation
}

// Where appends a list predicates to the PulseValueUpdate builder.
func (_u *PulseValueUpdate) Where(ps ...predicate.PulseValue) *PulseValueUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *PulseValueUpdate) SetTimestamp(v uint) *PulseValueUpdate {
	_u.mutation.ResetTimestamp()
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *PulseValueUpdate) SetNillableTimestamp(v *uint) *PulseValueUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// AddTimestamp adds value to the "timestamp" field.
func (_u *PulseValueUpdate) AddTimestamp(v int) *PulseValueUpdate {
	_u.mutation.AddTimestamp(v)
	return _u
}

// SetType sets the "type" field.
func (_u *PulseValueUpdate) SetType(v string) *PulseValueUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PulseValueUpdate) SetNillableType(v *string) *PulseValueUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *PulseValueUpdate) SetKey(v string) *PulseValueUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PulseValueUpdate) SetNillableKey(v *string) *PulseValueUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *PulseValueUpdate) SetKeyHash(v []byte) *PulseValueUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// ClearKeyHash clears the value of the "key_hash" field.
func (_u *PulseValueUpdate) ClearKeyHash() *PulseValueUpdate {
	_u.mutation.ClearKeyHash()
	return _u
}

// SetValue sets the "value" field.
func (_u *PulseValueUpdate) SetValue(v string) *PulseValueUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *PulseValueUpdate) SetNillableValue(v *string) *PulseValueUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// Mutation returns the PulseValueMutation object of the builder.
func (_u *PulseValueUpdate) Mutation() *PulseValueMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PulseValueUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PulseValueUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PulseValueUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PulseValueUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PulseValueUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pulsevalue.Table, pulsevalue.Columns, sqlgraph.NewFieldSpec(pulsevalue.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(pulsevalue.FieldTimestamp, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedTimestamp(); ok {
		_spec.AddField(pulsevalue.FieldTimestamp, field.TypeUint, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(pulsevalue.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(pulsevalue.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(pulsevalue.FieldKeyHash, field.TypeBytes, value)
	}
	if _u.mutation.KeyHashCleared() {
		_spec.ClearField(pulsevalue.FieldKeyHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(pulsevalue.FieldValue, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pulsevalue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PulseValueUpdateOne is the builder for updating a single PulseValue entity.
type PulseValueUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PulseValueMutation
}

// SetTimestamp sets the "timestamp" field.
func (_u *PulseValueUpdateOne) SetTimestamp(v uint) *PulseValueUpdateOne {
	_u.mutation.ResetTimestamp()
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *PulseValueUpdateOne) SetNillableTimestamp(v *uint) *PulseValueUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// AddTimestamp adds value to the "timestamp" field.
func (_u *PulseValueUpdateOne) AddTimestamp(v int) *PulseValueUpdateOne {
	_u.mutation.AddTimestamp(v)
	return _u
}

// SetType sets the "type" field.
func (_u *PulseValueUpdateOne) SetType(v string) *PulseValueUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PulseValueUpdateOne) SetNillableType(v *string) *PulseValueUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *PulseValueUpdateOne) SetKey(v string) *PulseValueUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PulseValueUpdateOne) SetNillableKey(v *string) *PulseValueUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *PulseValueUpdateOne) SetKeyHash(v []byte) *PulseValueUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// ClearKeyHash clears the value of the "key_hash" field.
func (_u *PulseValueUpdateOne) ClearKeyHash() *PulseValueUpdateOne {
	_u.mutation.ClearKeyHash()
	return _u
}

// SetValue sets the "value" field.
func (_u *PulseValueUpdateOne) SetValue(v string) *PulseValueUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *PulseValueUpdateOne) SetNillableValue(v *string) *PulseValueUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// Mutation returns the PulseValueMutation object of the builder.
func (_u *PulseValueUpdateOne) Mutation() *PulseValueMutation {
	return _u.mutation
}

// Where appends a list predicates to the PulseValueUpdate builder.
func (_u *PulseValueUpdateOne) Where(ps ...predicate.PulseValue) *PulseValueUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PulseValueUpdateOne) Select(field string, fields ...string) *PulseValueUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PulseValue entity.
func (_u *PulseValueUpdateOne) Save(ctx context.Context) (*PulseValue, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PulseValueUpdateOne) SaveX(ctx context.Context) *PulseValue {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PulseValueUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PulseValueUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PulseValueUpdateOne) sqlSave(ctx context.Context) (_node *PulseValue, err error) {
	_spec := sqlgraph.NewUpdateSpec(pulsevalue.Table, pulsevalue.Columns, sqlgraph.NewFieldSpec(pulsevalue.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PulseValue.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pulsevalue.FieldID)
		for _, f := range fields {
			if !pulsevalue.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pulsevalue.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(pulsevalue.FieldTimestamp, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedTimestamp(); ok {
		_spec.AddField(pulsevalue.FieldTimestamp, field.TypeUint, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(pulsevalue.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(pulsevalue.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(pulsevalue.FieldKeyHash, field.TypeBytes, value)
	}
	if _u.mutation.KeyHashCleared() {
		_spec.ClearField(pulsevalue.FieldKeyHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(pulsevalue.FieldValue, field.TypeString, value)
	}
	_node = &PulseValue{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pulsevalue.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
