// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/pulseentry"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PulseEntryCreate is the builder for creating a PulseEntry entity.
type PulseEntryCreate struct {
	config
	mutation *PulseEntryMutation
	hooks    []Hook
}

// SetTimestamp sets the "timestamp" field.
func (_c *PulseEntryCreate) SetTimestamp(v uint) *PulseEntryCreate {
	_c.mutation.SetTimestamp(v)
	return _c
}

// SetType sets the "type" field.
func (_c *PulseEntryCreate) SetType(v string) *PulseEntryCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetKey sets the "key" field.
func (_c *PulseEntryCreate) SetKey(v string) *PulseEntryCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *PulseEntryCreate) SetKeyHash(v []byte) *PulseEntryCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetValue sets the "value" field.
func (_c *PulseEntryCreate) SetValue(v int64) *PulseEntryCreate {
	_c.mutation.SetValue(v)
	return _c
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_c *PulseEntryCreate) SetNillableValue(v *int64) *PulseEntryCreate {
	if v != nil {
		_c.SetValue(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PulseEntryCreate) SetID(v uint64) *PulseEntryCreate {
	_c.mutation.SetID(v)
	return _c
}

// Mutation returns the PulseEntryMutation object of the builder.
func (_c *PulseEntryCreate) Mutation() *PulseEntryMutation {
	return _c.mutation
}

// Save creates the PulseEntry in the database.
func (_c *PulseEntryCreate) Save(ctx context.Context) (*PulseEntry, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PulseEntryCreate) SaveX(ctx context.Context) *PulseEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PulseEntryCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PulseEntryCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PulseEntryCreate) check() error {
	if _, ok := _c.mutation.Timestamp(); !ok {
		return &ValidationError{Name: "timestamp", err: errors.New(`ent: missing required field "PulseEntry.timestamp"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "PulseEntry.type"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "PulseEntry.key"`)}
	}
	return nil
}

func (_c *PulseEntryCreate) sqlSave(ctx context.Context) (*PulseEntry, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PulseEntryCreate) createSpec() (*PulseEntry, *sqlgraph.CreateSpec) {
	var (
		_node = &PulseEntry{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pulseentry.Table, sqlgraph.NewFieldSpec(pulseentry.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Timestamp(); ok {
		_spec.SetField(pulseentry.FieldTimestamp, field.TypeUint, value)
		_node.Timestamp = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(pulseentry.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(pulseentry.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(pulseentry.FieldKeyHash, field.TypeBytes, value)
		_node.KeyHash = &value
	}
	if value, ok := _c.mutation.Value(); ok {
		_spec.SetField(pulseentry.FieldValue, field.TypeInt64, value)
		_node.Value = &value
	}
	return _node, _spec
}

// PulseEntryCreateBulk is the builder for creating many PulseEntry entities in bulk.
type PulseEntryCreateBulk struct {
	config
	err      error
	builders []*PulseEntryCreate
}

// Save creates the PulseEntry entities in the database.
func (_c *PulseEntryCreateBulk) Save(ctx context.Context) ([]*PulseEntry, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PulseEntry, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PulseEntryMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PulseEntryCreateBulk) SaveX(ctx context.Context) []*PulseEntry {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PulseEntryCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PulseEntryCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
