// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"glintfed/ent/predicate"
	"glintfed/ent/pulseaggregate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PulseAggregateDelete is the builder for deleting a PulseAggregate entity.
type PulseAggregateDelete struct {
	config
	hooks    []Hook
	mutation *PulseAggregateMutation
}

// Where appends a list predicates to the PulseAggregateDelete builder.
func (_d *PulseAggregateDelete) Where(ps ...predicate.PulseAggregate) *PulseAggregateDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PulseAggregateDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PulseAggregateDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PulseAggregateDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pulseaggregate.Table, sqlgraph.NewFieldSpec(pulseaggregate.FieldID, field.TypeUint64))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PulseAggregateDeleteOne is the builder for deleting a single PulseAggregate entity.
type PulseAggregateDeleteOne struct {
	_d *PulseAggregateDelete
}

// Where appends a list predicates to the PulseAggregateDelete builder.
func (_d *PulseAggregateDeleteOne) Where(ps ...predicate.PulseAggregate) *PulseAggregateDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PulseAggregateDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pulseaggregate.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PulseAggregateDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
