// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/predicate"
	"glintfed/ent/pulseentry"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// PulseEntryUpdate is the builder for updating PulseEntry entities.
type PulseEntryUpdate struct {
	config
	hooks    []Hook
	mutation *PulseEntryMutation
}

// Where appends a list predicates to the PulseEntryUpdate builder.
func (_u *PulseEntryUpdate) Where(ps ...predicate.PulseEntry) *PulseEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTimestamp sets the "timestamp" field.
func (_u *PulseEntryUpdate) SetTimestamp(v uint) *PulseEntryUpdate {
	_u.mutation.ResetTimestamp()
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *PulseEntryUpdate) SetNillableTimestamp(v *uint) *PulseEntryUpdate {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// AddTimestamp adds value to the "timestamp" field.
func (_u *PulseEntryUpdate) AddTimestamp(v int) *PulseEntryUpdate {
	_u.mutation.AddTimestamp(v)
	return _u
}

// SetType sets the "type" field.
func (_u *PulseEntryUpdate) SetType(v string) *PulseEntryUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PulseEntryUpdate) SetNillableType(v *string) *PulseEntryUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *PulseEntryUpdate) SetKey(v string) *PulseEntryUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PulseEntryUpdate) SetNillableKey(v *string) *PulseEntryUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *PulseEntryUpdate) SetKeyHash(v []byte) *PulseEntryUpdate {
	_u.mutation.SetKeyHash(v)
	return _u
}

// ClearKeyHash clears the value of the "key_hash" field.
func (_u *PulseEntryUpdate) ClearKeyHash() *PulseEntryUpdate {
	_u.mutation.ClearKeyHash()
	return _u
}

// SetValue sets the "value" field.
func (_u *PulseEntryUpdate) SetValue(v int64) *PulseEntryUpdate {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *PulseEntryUpdate) SetNillableValue(v *int64) *PulseEntryUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *PulseEntryUpdate) AddValue(v int64) *PulseEntryUpdate {
	_u.mutation.AddValue(v)
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *PulseEntryUpdate) ClearValue() *PulseEntryUpdate {
	_u.mutation.ClearValue()
	return _u
}

// Mutation returns the PulseEntryMutation object of the builder.
func (_u *PulseEntryUpdate) Mutation() *PulseEntryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PulseEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PulseEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PulseEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PulseEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PulseEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(pulseentry.Table, pulseentry.Columns, sqlgraph.NewFieldSpec(pulseentry.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(pulseentry.FieldTimestamp, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedTimestamp(); ok {
		_spec.AddField(pulseentry.FieldTimestamp, field.TypeUint, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(pulseentry.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(pulseentry.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(pulseentry.FieldKeyHash, field.TypeBytes, value)
	}
	if _u.mutation.KeyHashCleared() {
		_spec.ClearField(pulseentry.FieldKeyHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(pulseentry.FieldValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(pulseentry.FieldValue, field.TypeInt64, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(pulseentry.FieldValue, field.TypeInt64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pulseentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PulseEntryUpdateOne is the builder for updating a single PulseEntry entity.
type PulseEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PulseEntryMutation
}

// SetTimestamp sets the "timestamp" field.
func (_u *PulseEntryUpdateOne) SetTimestamp(v uint) *PulseEntryUpdateOne {
	_u.mutation.ResetTimestamp()
	_u.mutation.SetTimestamp(v)
	return _u
}

// SetNillableTimestamp sets the "timestamp" field if the given value is not nil.
func (_u *PulseEntryUpdateOne) SetNillableTimestamp(v *uint) *PulseEntryUpdateOne {
	if v != nil {
		_u.SetTimestamp(*v)
	}
	return _u
}

// AddTimestamp adds value to the "timestamp" field.
func (_u *PulseEntryUpdateOne) AddTimestamp(v int) *PulseEntryUpdateOne {
	_u.mutation.AddTimestamp(v)
	return _u
}

// SetType sets the "type" field.
func (_u *PulseEntryUpdateOne) SetType(v string) *PulseEntryUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *PulseEntryUpdateOne) SetNillableType(v *string) *PulseEntryUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetKey sets the "key" field.
func (_u *PulseEntryUpdateOne) SetKey(v string) *PulseEntryUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *PulseEntryUpdateOne) SetNillableKey(v *string) *PulseEntryUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetKeyHash sets the "key_hash" field.
func (_u *PulseEntryUpdateOne) SetKeyHash(v []byte) *PulseEntryUpdateOne {
	_u.mutation.SetKeyHash(v)
	return _u
}

// ClearKeyHash clears the value of the "key_hash" field.
func (_u *PulseEntryUpdateOne) ClearKeyHash() *PulseEntryUpdateOne {
	_u.mutation.ClearKeyHash()
	return _u
}

// SetValue sets the "value" field.
func (_u *PulseEntryUpdateOne) SetValue(v int64) *PulseEntryUpdateOne {
	_u.mutation.ResetValue()
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *PulseEntryUpdateOne) SetNillableValue(v *int64) *PulseEntryUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// AddValue adds value to the "value" field.
func (_u *PulseEntryUpdateOne) AddValue(v int64) *PulseEntryUpdateOne {
	_u.mutation.AddValue(v)
	return _u
}

// ClearValue clears the value of the "value" field.
func (_u *PulseEntryUpdateOne) ClearValue() *PulseEntryUpdateOne {
	_u.mutation.ClearValue()
	return _u
}

// Mutation returns the PulseEntryMutation object of the builder.
func (_u *PulseEntryUpdateOne) Mutation() *PulseEntryMutation {
	return _u.mutation
}

// Where appends a list predicates to the PulseEntryUpdate builder.
func (_u *PulseEntryUpdateOne) Where(ps ...predicate.PulseEntry) *PulseEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PulseEntryUpdateOne) Select(field string, fields ...string) *PulseEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PulseEntry entity.
func (_u *PulseEntryUpdateOne) Save(ctx context.Context) (*PulseEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PulseEntryUpdateOne) SaveX(ctx context.Context) *PulseEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PulseEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PulseEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *PulseEntryUpdateOne) sqlSave(ctx context.Context) (_node *PulseEntry, err error) {
	_spec := sqlgraph.NewUpdateSpec(pulseentry.Table, pulseentry.Columns, sqlgraph.NewFieldSpec(pulseentry.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PulseEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pulseentry.FieldID)
		for _, f := range fields {
			if !pulseentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pulseentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Timestamp(); ok {
		_spec.SetField(pulseentry.FieldTimestamp, field.TypeUint, value)
	}
	if value, ok := _u.mutation.AddedTimestamp(); ok {
		_spec.AddField(pulseentry.FieldTimestamp, field.TypeUint, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(pulseentry.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(pulseentry.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.KeyHash(); ok {
		_spec.SetField(pulseentry.FieldKeyHash, field.TypeBytes, value)
	}
	if _u.mutation.KeyHashCleared() {
		_spec.ClearField(pulseentry.FieldKeyHash, field.TypeBytes)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(pulseentry.FieldValue, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedValue(); ok {
		_spec.AddField(pulseentry.FieldValue, field.TypeInt64, value)
	}
	if _u.mutation.ValueCleared() {
		_spec.ClearField(pulseentry.FieldValue, field.TypeInt64)
	}
	_node = &PulseEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pulseentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
