// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"glintfed/ent/pushsubscription"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// PushSubscription is the model entity for the PushSubscription schema.
type PushSubscription struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// SubscribableType holds the value of the "subscribable_type" field.
	SubscribableType string `json:"subscribable_type,omitempty"`
	// SubscribableID holds the value of the "subscribable_id" field.
	SubscribableID uint64 `json:"subscribable_id,omitempty"`
	// Endpoint holds the value of the "endpoint" field.
	Endpoint string `json:"endpoint,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey *string `json:"public_key,omitempty"`
	// AuthToken holds the value of the "auth_token" field.
	AuthToken *string `json:"auth_token,omitempty"`
	// ContentEncoding holds the value of the "content_encoding" field.
	ContentEncoding *string `json:"content_encoding,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PushSubscription) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pushsubscription.FieldID, pushsubscription.FieldSubscribableID:
			values[i] = new(sql.NullInt64)
		case pushsubscription.FieldSubscribableType, pushsubscription.FieldEndpoint, pushsubscription.FieldPublicKey, pushsubscription.FieldAuthToken, pushsubscription.FieldContentEncoding:
			values[i] = new(sql.NullString)
		case pushsubscription.FieldCreatedAt, pushsubscription.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PushSubscription fields.
func (_m *PushSubscription) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pushsubscription.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case pushsubscription.FieldSubscribableType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subscribable_type", values[i])
			} else if value.Valid {
				_m.SubscribableType = value.String
			}
		case pushsubscription.FieldSubscribableID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field subscribable_id", values[i])
			} else if value.Valid {
				_m.SubscribableID = uint64(value.Int64)
			}
		case pushsubscription.FieldEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field endpoint", values[i])
			} else if value.Valid {
				_m.Endpoint = value.String
			}
		case pushsubscription.FieldPublicKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value.Valid {
				_m.PublicKey = new(string)
				*_m.PublicKey = value.String
			}
		case pushsubscription.FieldAuthToken:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_token", values[i])
			} else if value.Valid {
				_m.AuthToken = new(string)
				*_m.AuthToken = value.String
			}
		case pushsubscription.FieldContentEncoding:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_encoding", values[i])
			} else if value.Valid {
				_m.ContentEncoding = new(string)
				*_m.ContentEncoding = value.String
			}
		case pushsubscription.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case pushsubscription.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PushSubscription.
// This includes values selected through modifiers, order, etc.
func (_m *PushSubscription) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PushSubscription.
// Note that you need to call PushSubscription.Unwrap() before calling this method if this PushSubscription
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PushSubscription) Update() *PushSubscriptionUpdateOne {
	return NewPushSubscriptionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PushSubscription entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PushSubscription) Unwrap() *PushSubscription {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PushSubscription is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PushSubscription) String() string {
	var builder strings.Builder
	builder.WriteString("PushSubscription(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("subscribable_type=")
	builder.WriteString(_m.SubscribableType)
	builder.WriteString(", ")
	builder.WriteString("subscribable_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SubscribableID))
	builder.WriteString(", ")
	builder.WriteString("endpoint=")
	builder.WriteString(_m.Endpoint)
	builder.WriteString(", ")
	if v := _m.PublicKey; v != nil {
		builder.WriteString("public_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AuthToken; v != nil {
		builder.WriteString("auth_token=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ContentEncoding; v != nil {
		builder.WriteString("content_encoding=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PushSubscriptions is a parsable slice of PushSubscription.
type PushSubscriptions []*PushSubscription
