// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/profile"
	"glintfed/ent/report"
	"glintfed/ent/status"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ReportCreate is the builder for creating a Report entity.
type ReportCreate struct {
	config
	mutation *ReportMutation
	hooks    []Hook
}

// SetProfileID sets the "profile_id" field.
func (_c *ReportCreate) SetProfileID(v uint64) *ReportCreate {
	_c.mutation.SetProfileID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *ReportCreate) SetUserID(v uint64) *ReportCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_c *ReportCreate) SetNillableUserID(v *uint64) *ReportCreate {
	if v != nil {
		_c.SetUserID(*v)
	}
	return _c
}

// SetObjectID sets the "object_id" field.
func (_c *ReportCreate) SetObjectID(v uint64) *ReportCreate {
	_c.mutation.SetObjectID(v)
	return _c
}

// SetObjectType sets the "object_type" field.
func (_c *ReportCreate) SetObjectType(v string) *ReportCreate {
	_c.mutation.SetObjectType(v)
	return _c
}

// SetNillableObjectType sets the "object_type" field if the given value is not nil.
func (_c *ReportCreate) SetNillableObjectType(v *string) *ReportCreate {
	if v != nil {
		_c.SetObjectType(*v)
	}
	return _c
}

// SetReportedProfileID sets the "reported_profile_id" field.
func (_c *ReportCreate) SetReportedProfileID(v uint64) *ReportCreate {
	_c.mutation.SetReportedProfileID(v)
	return _c
}

// SetNillableReportedProfileID sets the "reported_profile_id" field if the given value is not nil.
func (_c *ReportCreate) SetNillableReportedProfileID(v *uint64) *ReportCreate {
	if v != nil {
		_c.SetReportedProfileID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ReportCreate) SetType(v string) *ReportCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_c *ReportCreate) SetNillableType(v *string) *ReportCreate {
	if v != nil {
		_c.SetType(*v)
	}
	return _c
}

// SetMessage sets the "message" field.
func (_c *ReportCreate) SetMessage(v string) *ReportCreate {
	_c.mutation.SetMessage(v)
	return _c
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_c *ReportCreate) SetNillableMessage(v *string) *ReportCreate {
	if v != nil {
		_c.SetMessage(*v)
	}
	return _c
}

// SetAdminSeen sets the "admin_seen" field.
func (_c *ReportCreate) SetAdminSeen(v time.Time) *ReportCreate {
	_c.mutation.SetAdminSeen(v)
	return _c
}

// SetNillableAdminSeen sets the "admin_seen" field if the given value is not nil.
func (_c *ReportCreate) SetNillableAdminSeen(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetAdminSeen(*v)
	}
	return _c
}

// SetNotInterested sets the "not_interested" field.
func (_c *ReportCreate) SetNotInterested(v bool) *ReportCreate {
	_c.mutation.SetNotInterested(v)
	return _c
}

// SetSpam sets the "spam" field.
func (_c *ReportCreate) SetSpam(v bool) *ReportCreate {
	_c.mutation.SetSpam(v)
	return _c
}

// SetNsfw sets the "nsfw" field.
func (_c *ReportCreate) SetNsfw(v bool) *ReportCreate {
	_c.mutation.SetNsfw(v)
	return _c
}

// SetAbusive sets the "abusive" field.
func (_c *ReportCreate) SetAbusive(v bool) *ReportCreate {
	_c.mutation.SetAbusive(v)
	return _c
}

// SetMeta sets the "meta" field.
func (_c *ReportCreate) SetMeta(v string) *ReportCreate {
	_c.mutation.SetMeta(v)
	return _c
}

// SetNillableMeta sets the "meta" field if the given value is not nil.
func (_c *ReportCreate) SetNillableMeta(v *string) *ReportCreate {
	if v != nil {
		_c.SetMeta(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReportCreate) SetCreatedAt(v time.Time) *ReportCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillableCreatedAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ReportCreate) SetUpdatedAt(v time.Time) *ReportCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ReportCreate) SetNillableUpdatedAt(v *time.Time) *ReportCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ReportCreate) SetID(v uint64) *ReportCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetReporterID sets the "reporter" edge to the Profile entity by ID.
func (_c *ReportCreate) SetReporterID(id uint64) *ReportCreate {
	_c.mutation.SetReporterID(id)
	return _c
}

// SetReporter sets the "reporter" edge to the Profile entity.
func (_c *ReportCreate) SetReporter(v *Profile) *ReportCreate {
	return _c.SetReporterID(v.ID)
}

// SetStatusID sets the "status" edge to the Status entity by ID.
func (_c *ReportCreate) SetStatusID(id uint64) *ReportCreate {
	_c.mutation.SetStatusID(id)
	return _c
}

// SetStatus sets the "status" edge to the Status entity.
func (_c *ReportCreate) SetStatus(v *Status) *ReportCreate {
	return _c.SetStatusID(v.ID)
}

// SetReportedUserID sets the "reportedUser" edge to the Profile entity by ID.
func (_c *ReportCreate) SetReportedUserID(id uint64) *ReportCreate {
	_c.mutation.SetReportedUserID(id)
	return _c
}

// SetNillableReportedUserID sets the "reportedUser" edge to the Profile entity by ID if the given value is not nil.
func (_c *ReportCreate) SetNillableReportedUserID(id *uint64) *ReportCreate {
	if id != nil {
		_c = _c.SetReportedUserID(*id)
	}
	return _c
}

// SetReportedUser sets the "reportedUser" edge to the Profile entity.
func (_c *ReportCreate) SetReportedUser(v *Profile) *ReportCreate {
	return _c.SetReportedUserID(v.ID)
}

// Mutation returns the ReportMutation object of the builder.
func (_c *ReportCreate) Mutation() *ReportMutation {
	return _c.mutation
}

// Save creates the Report in the database.
func (_c *ReportCreate) Save(ctx context.Context) (*Report, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReportCreate) SaveX(ctx context.Context) *Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReportCreate) check() error {
	if _, ok := _c.mutation.ProfileID(); !ok {
		return &ValidationError{Name: "profile_id", err: errors.New(`ent: missing required field "Report.profile_id"`)}
	}
	if _, ok := _c.mutation.ObjectID(); !ok {
		return &ValidationError{Name: "object_id", err: errors.New(`ent: missing required field "Report.object_id"`)}
	}
	if _, ok := _c.mutation.NotInterested(); !ok {
		return &ValidationError{Name: "not_interested", err: errors.New(`ent: missing required field "Report.not_interested"`)}
	}
	if _, ok := _c.mutation.Spam(); !ok {
		return &ValidationError{Name: "spam", err: errors.New(`ent: missing required field "Report.spam"`)}
	}
	if _, ok := _c.mutation.Nsfw(); !ok {
		return &ValidationError{Name: "nsfw", err: errors.New(`ent: missing required field "Report.nsfw"`)}
	}
	if _, ok := _c.mutation.Abusive(); !ok {
		return &ValidationError{Name: "abusive", err: errors.New(`ent: missing required field "Report.abusive"`)}
	}
	if len(_c.mutation.ReporterIDs()) == 0 {
		return &ValidationError{Name: "reporter", err: errors.New(`ent: missing required edge "Report.reporter"`)}
	}
	if len(_c.mutation.StatusIDs()) == 0 {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required edge "Report.status"`)}
	}
	return nil
}

func (_c *ReportCreate) sqlSave(ctx context.Context) (*Report, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = uint64(id)
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReportCreate) createSpec() (*Report, *sqlgraph.CreateSpec) {
	var (
		_node = &Report{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(report.Table, sqlgraph.NewFieldSpec(report.FieldID, field.TypeUint64))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(report.FieldUserID, field.TypeUint64, value)
		_node.UserID = &value
	}
	if value, ok := _c.mutation.ObjectType(); ok {
		_spec.SetField(report.FieldObjectType, field.TypeString, value)
		_node.ObjectType = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(report.FieldType, field.TypeString, value)
		_node.Type = &value
	}
	if value, ok := _c.mutation.Message(); ok {
		_spec.SetField(report.FieldMessage, field.TypeString, value)
		_node.Message = &value
	}
	if value, ok := _c.mutation.AdminSeen(); ok {
		_spec.SetField(report.FieldAdminSeen, field.TypeTime, value)
		_node.AdminSeen = &value
	}
	if value, ok := _c.mutation.NotInterested(); ok {
		_spec.SetField(report.FieldNotInterested, field.TypeBool, value)
		_node.NotInterested = value
	}
	if value, ok := _c.mutation.Spam(); ok {
		_spec.SetField(report.FieldSpam, field.TypeBool, value)
		_node.Spam = value
	}
	if value, ok := _c.mutation.Nsfw(); ok {
		_spec.SetField(report.FieldNsfw, field.TypeBool, value)
		_node.Nsfw = value
	}
	if value, ok := _c.mutation.Abusive(); ok {
		_spec.SetField(report.FieldAbusive, field.TypeBool, value)
		_node.Abusive = value
	}
	if value, ok := _c.mutation.Meta(); ok {
		_spec.SetField(report.FieldMeta, field.TypeString, value)
		_node.Meta = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(report.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(report.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	if nodes := _c.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   report.ReporterTable,
			Columns: []string{report.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProfileID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.StatusTable,
			Columns: []string{report.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ObjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ReportedUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.ReportedUserTable,
			Columns: []string{report.ReportedUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ReportedProfileID = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ReportCreateBulk is the builder for creating many Report entities in bulk.
type ReportCreateBulk struct {
	config
	err      error
	builders []*ReportCreate
}

// Save creates the Report entities in the database.
func (_c *ReportCreateBulk) Save(ctx context.Context) ([]*Report, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Report, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReportMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = uint64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReportCreateBulk) SaveX(ctx context.Context) []*Report {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReportCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReportCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
