// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/predicate"
	"glintfed/ent/session"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SessionUpdate is the builder for updating Session entities.
type SessionUpdate struct {
	config
	hooks    []Hook
	mutation *SessionMutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdate) Where(ps ...predicate.Session) *SessionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdate) SetUserID(v uint64) *SessionUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserID(v *uint64) *SessionUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SessionUpdate) AddUserID(v int64) *SessionUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SessionUpdate) ClearUserID() *SessionUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *SessionUpdate) SetIPAddress(v string) *SessionUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableIPAddress(v *string) *SessionUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *SessionUpdate) ClearIPAddress() *SessionUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SessionUpdate) SetUserAgent(v string) *SessionUpdate {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableUserAgent(v *string) *SessionUpdate {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *SessionUpdate) ClearUserAgent() *SessionUpdate {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SessionUpdate) SetPayload(v string) *SessionUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *SessionUpdate) SetNillablePayload(v *string) *SessionUpdate {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetLastActivity sets the "last_activity" field.
func (_u *SessionUpdate) SetLastActivity(v int) *SessionUpdate {
	_u.mutation.ResetLastActivity()
	_u.mutation.SetLastActivity(v)
	return _u
}

// SetNillableLastActivity sets the "last_activity" field if the given value is not nil.
func (_u *SessionUpdate) SetNillableLastActivity(v *int) *SessionUpdate {
	if v != nil {
		_u.SetLastActivity(*v)
	}
	return _u
}

// AddLastActivity adds value to the "last_activity" field.
func (_u *SessionUpdate) AddLastActivity(v int) *SessionUpdate {
	_u.mutation.AddLastActivity(v)
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdate) Mutation() *SessionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SessionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SessionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SessionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(session.FieldUserID, field.TypeUint64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(session.FieldUserID, field.TypeUint64)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(session.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(session.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(session.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(session.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastActivity(); ok {
		_spec.SetField(session.FieldLastActivity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastActivity(); ok {
		_spec.AddField(session.FieldLastActivity, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SessionUpdateOne is the builder for updating a single Session entity.
type SessionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SessionMutation
}

// SetUserID sets the "user_id" field.
func (_u *SessionUpdateOne) SetUserID(v uint64) *SessionUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserID(v *uint64) *SessionUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *SessionUpdateOne) AddUserID(v int64) *SessionUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *SessionUpdateOne) ClearUserID() *SessionUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *SessionUpdateOne) SetIPAddress(v string) *SessionUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableIPAddress(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *SessionUpdateOne) ClearIPAddress() *SessionUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetUserAgent sets the "user_agent" field.
func (_u *SessionUpdateOne) SetUserAgent(v string) *SessionUpdateOne {
	_u.mutation.SetUserAgent(v)
	return _u
}

// SetNillableUserAgent sets the "user_agent" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableUserAgent(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetUserAgent(*v)
	}
	return _u
}

// ClearUserAgent clears the value of the "user_agent" field.
func (_u *SessionUpdateOne) ClearUserAgent() *SessionUpdateOne {
	_u.mutation.ClearUserAgent()
	return _u
}

// SetPayload sets the "payload" field.
func (_u *SessionUpdateOne) SetPayload(v string) *SessionUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetNillablePayload sets the "payload" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillablePayload(v *string) *SessionUpdateOne {
	if v != nil {
		_u.SetPayload(*v)
	}
	return _u
}

// SetLastActivity sets the "last_activity" field.
func (_u *SessionUpdateOne) SetLastActivity(v int) *SessionUpdateOne {
	_u.mutation.ResetLastActivity()
	_u.mutation.SetLastActivity(v)
	return _u
}

// SetNillableLastActivity sets the "last_activity" field if the given value is not nil.
func (_u *SessionUpdateOne) SetNillableLastActivity(v *int) *SessionUpdateOne {
	if v != nil {
		_u.SetLastActivity(*v)
	}
	return _u
}

// AddLastActivity adds value to the "last_activity" field.
func (_u *SessionUpdateOne) AddLastActivity(v int) *SessionUpdateOne {
	_u.mutation.AddLastActivity(v)
	return _u
}

// Mutation returns the SessionMutation object of the builder.
func (_u *SessionUpdateOne) Mutation() *SessionMutation {
	return _u.mutation
}

// Where appends a list predicates to the SessionUpdate builder.
func (_u *SessionUpdateOne) Where(ps ...predicate.Session) *SessionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SessionUpdateOne) Select(field string, fields ...string) *SessionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Session entity.
func (_u *SessionUpdateOne) Save(ctx context.Context) (*Session, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SessionUpdateOne) SaveX(ctx context.Context) *Session {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SessionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SessionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *SessionUpdateOne) sqlSave(ctx context.Context) (_node *Session, err error) {
	_spec := sqlgraph.NewUpdateSpec(session.Table, session.Columns, sqlgraph.NewFieldSpec(session.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Session.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, session.FieldID)
		for _, f := range fields {
			if !session.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != session.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(session.FieldUserID, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(session.FieldUserID, field.TypeUint64, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(session.FieldUserID, field.TypeUint64)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(session.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(session.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.UserAgent(); ok {
		_spec.SetField(session.FieldUserAgent, field.TypeString, value)
	}
	if _u.mutation.UserAgentCleared() {
		_spec.ClearField(session.FieldUserAgent, field.TypeString)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(session.FieldPayload, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastActivity(); ok {
		_spec.SetField(session.FieldLastActivity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLastActivity(); ok {
		_spec.AddField(session.FieldLastActivity, field.TypeInt, value)
	}
	_node = &Session{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{session.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
