// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"glintfed/ent/directmessage"
	"glintfed/ent/like"
	"glintfed/ent/media"
	"glintfed/ent/place"
	"glintfed/ent/predicate"
	"glintfed/ent/profile"
	"glintfed/ent/status"
	"glintfed/ent/statusedit"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StatusQuery is the builder for querying Status entities.
type StatusQuery struct {
	config
	ctx               *QueryContext
	order             []status.OrderOption
	inters            []Interceptor
	predicates        []predicate.Status
	withProfile       *ProfileQuery
	withMedia         *MediaQuery
	withFirstMedia    *MediaQuery
	withLikes         *LikeQuery
	withComments      *StatusQuery
	withShares        *StatusQuery
	withPlace         *PlaceQuery
	withDirectMessage *DirectMessageQuery
	withEdits         *StatusEditQuery
	withFKs           bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StatusQuery builder.
func (_q *StatusQuery) Where(ps ...predicate.Status) *StatusQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *StatusQuery) Limit(limit int) *StatusQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *StatusQuery) Offset(offset int) *StatusQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *StatusQuery) Unique(unique bool) *StatusQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *StatusQuery) Order(o ...status.OrderOption) *StatusQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProfile chains the current query on the "profile" edge.
func (_q *StatusQuery) QueryProfile() *ProfileQuery {
	query := (&ProfileClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(status.Table, status.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, status.ProfileTable, status.ProfileColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryMedia chains the current query on the "media" edge.
func (_q *StatusQuery) QueryMedia() *MediaQuery {
	query := (&MediaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(status.Table, status.FieldID, selector),
			sqlgraph.To(media.Table, media.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, status.MediaTable, status.MediaColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryFirstMedia chains the current query on the "firstMedia" edge.
func (_q *StatusQuery) QueryFirstMedia() *MediaQuery {
	query := (&MediaClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(status.Table, status.FieldID, selector),
			sqlgraph.To(media.Table, media.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, status.FirstMediaTable, status.FirstMediaColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryLikes chains the current query on the "likes" edge.
func (_q *StatusQuery) QueryLikes() *LikeQuery {
	query := (&LikeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(status.Table, status.FieldID, selector),
			sqlgraph.To(like.Table, like.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, status.LikesTable, status.LikesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryComments chains the current query on the "comments" edge.
func (_q *StatusQuery) QueryComments() *StatusQuery {
	query := (&StatusClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(status.Table, status.FieldID, selector),
			sqlgraph.To(status.Table, status.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, status.CommentsTable, status.CommentsPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryShares chains the current query on the "shares" edge.
func (_q *StatusQuery) QueryShares() *StatusQuery {
	query := (&StatusClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(status.Table, status.FieldID, selector),
			sqlgraph.To(status.Table, status.FieldID),
			sqlgraph.Edge(sqlgraph.M2M, false, status.SharesTable, status.SharesPrimaryKey...),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlace chains the current query on the "place" edge.
func (_q *StatusQuery) QueryPlace() *PlaceQuery {
	query := (&PlaceClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(status.Table, status.FieldID, selector),
			sqlgraph.To(place.Table, place.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, status.PlaceTable, status.PlaceColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDirectMessage chains the current query on the "directMessage" edge.
func (_q *StatusQuery) QueryDirectMessage() *DirectMessageQuery {
	query := (&DirectMessageClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(status.Table, status.FieldID, selector),
			sqlgraph.To(directmessage.Table, directmessage.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, status.DirectMessageTable, status.DirectMessageColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEdits chains the current query on the "edits" edge.
func (_q *StatusQuery) QueryEdits() *StatusEditQuery {
	query := (&StatusEditClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(status.Table, status.FieldID, selector),
			sqlgraph.To(statusedit.Table, statusedit.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, status.EditsTable, status.EditsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Status entity from the query.
// Returns a *NotFoundError when no Status was found.
func (_q *StatusQuery) First(ctx context.Context) (*Status, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{status.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *StatusQuery) FirstX(ctx context.Context) *Status {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Status ID from the query.
// Returns a *NotFoundError when no Status ID was found.
func (_q *StatusQuery) FirstID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{status.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *StatusQuery) FirstIDX(ctx context.Context) uint64 {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Status entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Status entity is found.
// Returns a *NotFoundError when no Status entities are found.
func (_q *StatusQuery) Only(ctx context.Context) (*Status, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{status.Label}
	default:
		return nil, &NotSingularError{status.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *StatusQuery) OnlyX(ctx context.Context) *Status {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Status ID in the query.
// Returns a *NotSingularError when more than one Status ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *StatusQuery) OnlyID(ctx context.Context) (id uint64, err error) {
	var ids []uint64
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{status.Label}
	default:
		err = &NotSingularError{status.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *StatusQuery) OnlyIDX(ctx context.Context) uint64 {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StatusSlice.
func (_q *StatusQuery) All(ctx context.Context) ([]*Status, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Status, *StatusQuery]()
	return withInterceptors[[]*Status](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *StatusQuery) AllX(ctx context.Context) []*Status {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Status IDs.
func (_q *StatusQuery) IDs(ctx context.Context) (ids []uint64, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(status.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *StatusQuery) IDsX(ctx context.Context) []uint64 {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *StatusQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*StatusQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *StatusQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *StatusQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *StatusQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StatusQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *StatusQuery) Clone() *StatusQuery {
	if _q == nil {
		return nil
	}
	return &StatusQuery{
		config:            _q.config,
		ctx:               _q.ctx.Clone(),
		order:             append([]status.OrderOption{}, _q.order...),
		inters:            append([]Interceptor{}, _q.inters...),
		predicates:        append([]predicate.Status{}, _q.predicates...),
		withProfile:       _q.withProfile.Clone(),
		withMedia:         _q.withMedia.Clone(),
		withFirstMedia:    _q.withFirstMedia.Clone(),
		withLikes:         _q.withLikes.Clone(),
		withComments:      _q.withComments.Clone(),
		withShares:        _q.withShares.Clone(),
		withPlace:         _q.withPlace.Clone(),
		withDirectMessage: _q.withDirectMessage.Clone(),
		withEdits:         _q.withEdits.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProfile tells the query-builder to eager-load the nodes that are connected to
// the "profile" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StatusQuery) WithProfile(opts ...func(*ProfileQuery)) *StatusQuery {
	query := (&ProfileClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProfile = query
	return _q
}

// WithMedia tells the query-builder to eager-load the nodes that are connected to
// the "media" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StatusQuery) WithMedia(opts ...func(*MediaQuery)) *StatusQuery {
	query := (&MediaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withMedia = query
	return _q
}

// WithFirstMedia tells the query-builder to eager-load the nodes that are connected to
// the "firstMedia" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StatusQuery) WithFirstMedia(opts ...func(*MediaQuery)) *StatusQuery {
	query := (&MediaClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withFirstMedia = query
	return _q
}

// WithLikes tells the query-builder to eager-load the nodes that are connected to
// the "likes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StatusQuery) WithLikes(opts ...func(*LikeQuery)) *StatusQuery {
	query := (&LikeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withLikes = query
	return _q
}

// WithComments tells the query-builder to eager-load the nodes that are connected to
// the "comments" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StatusQuery) WithComments(opts ...func(*StatusQuery)) *StatusQuery {
	query := (&StatusClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withComments = query
	return _q
}

// WithShares tells the query-builder to eager-load the nodes that are connected to
// the "shares" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StatusQuery) WithShares(opts ...func(*StatusQuery)) *StatusQuery {
	query := (&StatusClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withShares = query
	return _q
}

// WithPlace tells the query-builder to eager-load the nodes that are connected to
// the "place" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StatusQuery) WithPlace(opts ...func(*PlaceQuery)) *StatusQuery {
	query := (&PlaceClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlace = query
	return _q
}

// WithDirectMessage tells the query-builder to eager-load the nodes that are connected to
// the "directMessage" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StatusQuery) WithDirectMessage(opts ...func(*DirectMessageQuery)) *StatusQuery {
	query := (&DirectMessageClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDirectMessage = query
	return _q
}

// WithEdits tells the query-builder to eager-load the nodes that are connected to
// the "edits" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *StatusQuery) WithEdits(opts ...func(*StatusEditQuery)) *StatusQuery {
	query := (&StatusEditClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEdits = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		URI string `json:"uri,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Status.Query().
//		GroupBy(status.FieldURI).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *StatusQuery) GroupBy(field string, fields ...string) *StatusGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StatusGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = status.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		URI string `json:"uri,omitempty"`
//	}
//
//	client.Status.Query().
//		Select(status.FieldURI).
//		Scan(ctx, &v)
func (_q *StatusQuery) Select(fields ...string) *StatusSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &StatusSelect{StatusQuery: _q}
	sbuild.label = status.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StatusSelect configured with the given aggregations.
func (_q *StatusQuery) Aggregate(fns ...AggregateFunc) *StatusSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *StatusQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !status.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *StatusQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Status, error) {
	var (
		nodes       = []*Status{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [9]bool{
			_q.withProfile != nil,
			_q.withMedia != nil,
			_q.withFirstMedia != nil,
			_q.withLikes != nil,
			_q.withComments != nil,
			_q.withShares != nil,
			_q.withPlace != nil,
			_q.withDirectMessage != nil,
			_q.withEdits != nil,
		}
	)
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, status.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Status).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Status{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProfile; query != nil {
		if err := _q.loadProfile(ctx, query, nodes, nil,
			func(n *Status, e *Profile) { n.Edges.Profile = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withMedia; query != nil {
		if err := _q.loadMedia(ctx, query, nodes,
			func(n *Status) { n.Edges.Media = []*Media{} },
			func(n *Status, e *Media) { n.Edges.Media = append(n.Edges.Media, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withFirstMedia; query != nil {
		if err := _q.loadFirstMedia(ctx, query, nodes,
			func(n *Status) { n.Edges.FirstMedia = []*Media{} },
			func(n *Status, e *Media) { n.Edges.FirstMedia = append(n.Edges.FirstMedia, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withLikes; query != nil {
		if err := _q.loadLikes(ctx, query, nodes,
			func(n *Status) { n.Edges.Likes = []*Like{} },
			func(n *Status, e *Like) { n.Edges.Likes = append(n.Edges.Likes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withComments; query != nil {
		if err := _q.loadComments(ctx, query, nodes,
			func(n *Status) { n.Edges.Comments = []*Status{} },
			func(n *Status, e *Status) { n.Edges.Comments = append(n.Edges.Comments, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withShares; query != nil {
		if err := _q.loadShares(ctx, query, nodes,
			func(n *Status) { n.Edges.Shares = []*Status{} },
			func(n *Status, e *Status) { n.Edges.Shares = append(n.Edges.Shares, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPlace; query != nil {
		if err := _q.loadPlace(ctx, query, nodes, nil,
			func(n *Status, e *Place) { n.Edges.Place = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDirectMessage; query != nil {
		if err := _q.loadDirectMessage(ctx, query, nodes, nil,
			func(n *Status, e *DirectMessage) { n.Edges.DirectMessage = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEdits; query != nil {
		if err := _q.loadEdits(ctx, query, nodes,
			func(n *Status) { n.Edges.Edits = []*StatusEdit{} },
			func(n *Status, e *StatusEdit) { n.Edges.Edits = append(n.Edges.Edits, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *StatusQuery) loadProfile(ctx context.Context, query *ProfileQuery, nodes []*Status, init func(*Status), assign func(*Status, *Profile)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*Status)
	for i := range nodes {
		if nodes[i].ProfileID == nil {
			continue
		}
		fk := *nodes[i].ProfileID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(profile.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "profile_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *StatusQuery) loadMedia(ctx context.Context, query *MediaQuery, nodes []*Status, init func(*Status), assign func(*Status, *Media)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Status)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(media.FieldStatusID)
	}
	query.Where(predicate.Media(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(status.MediaColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StatusID
		if fk == nil {
			return fmt.Errorf(`foreign-key "status_id" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "status_id" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StatusQuery) loadFirstMedia(ctx context.Context, query *MediaQuery, nodes []*Status, init func(*Status), assign func(*Status, *Media)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Status)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Media(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(status.FirstMediaColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.status_first_media
		if fk == nil {
			return fmt.Errorf(`foreign-key "status_first_media" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "status_first_media" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StatusQuery) loadLikes(ctx context.Context, query *LikeQuery, nodes []*Status, init func(*Status), assign func(*Status, *Like)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Status)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(like.FieldStatusID)
	}
	query.Where(predicate.Like(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(status.LikesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StatusID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "status_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StatusQuery) loadComments(ctx context.Context, query *StatusQuery, nodes []*Status, init func(*Status), assign func(*Status, *Status)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Status)
	nids := make(map[uint64]map[*Status]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(status.CommentsTable)
		s.Join(joinT).On(s.C(status.FieldID), joinT.C(status.CommentsPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(status.CommentsPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(status.CommentsPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Status]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Status](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "comments" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *StatusQuery) loadShares(ctx context.Context, query *StatusQuery, nodes []*Status, init func(*Status), assign func(*Status, *Status)) error {
	edgeIDs := make([]driver.Value, len(nodes))
	byID := make(map[uint64]*Status)
	nids := make(map[uint64]map[*Status]struct{})
	for i, node := range nodes {
		edgeIDs[i] = node.ID
		byID[node.ID] = node
		if init != nil {
			init(node)
		}
	}
	query.Where(func(s *sql.Selector) {
		joinT := sql.Table(status.SharesTable)
		s.Join(joinT).On(s.C(status.FieldID), joinT.C(status.SharesPrimaryKey[1]))
		s.Where(sql.InValues(joinT.C(status.SharesPrimaryKey[0]), edgeIDs...))
		columns := s.SelectedColumns()
		s.Select(joinT.C(status.SharesPrimaryKey[0]))
		s.AppendSelect(columns...)
		s.SetDistinct(false)
	})
	if err := query.prepareQuery(ctx); err != nil {
		return err
	}
	qr := QuerierFunc(func(ctx context.Context, q Query) (Value, error) {
		return query.sqlAll(ctx, func(_ context.Context, spec *sqlgraph.QuerySpec) {
			assign := spec.Assign
			values := spec.ScanValues
			spec.ScanValues = func(columns []string) ([]any, error) {
				values, err := values(columns[1:])
				if err != nil {
					return nil, err
				}
				return append([]any{new(sql.NullInt64)}, values...), nil
			}
			spec.Assign = func(columns []string, values []any) error {
				outValue := uint64(values[0].(*sql.NullInt64).Int64)
				inValue := uint64(values[1].(*sql.NullInt64).Int64)
				if nids[inValue] == nil {
					nids[inValue] = map[*Status]struct{}{byID[outValue]: {}}
					return assign(columns[1:], values[1:])
				}
				nids[inValue][byID[outValue]] = struct{}{}
				return nil
			}
		})
	})
	neighbors, err := withInterceptors[[]*Status](ctx, query, qr, query.inters)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected "shares" node returned %v`, n.ID)
		}
		for kn := range nodes {
			assign(kn, n)
		}
	}
	return nil
}
func (_q *StatusQuery) loadPlace(ctx context.Context, query *PlaceQuery, nodes []*Status, init func(*Status), assign func(*Status, *Place)) error {
	ids := make([]uint64, 0, len(nodes))
	nodeids := make(map[uint64][]*Status)
	for i := range nodes {
		if nodes[i].PlaceID == nil {
			continue
		}
		fk := *nodes[i].PlaceID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(place.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "place_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *StatusQuery) loadDirectMessage(ctx context.Context, query *DirectMessageQuery, nodes []*Status, init func(*Status), assign func(*Status, *DirectMessage)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Status)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(directmessage.FieldStatusID)
	}
	query.Where(predicate.DirectMessage(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(status.DirectMessageColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.StatusID
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "status_id" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *StatusQuery) loadEdits(ctx context.Context, query *StatusEditQuery, nodes []*Status, init func(*Status), assign func(*Status, *StatusEdit)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[uint64]*Status)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.StatusEdit(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(status.EditsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.status_edits
		if fk == nil {
			return fmt.Errorf(`foreign-key "status_edits" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "status_edits" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *StatusQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *StatusQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(status.Table, status.Columns, sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, status.FieldID)
		for i := range fields {
			if fields[i] != status.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withProfile != nil {
			_spec.Node.AddColumnOnce(status.FieldProfileID)
		}
		if _q.withPlace != nil {
			_spec.Node.AddColumnOnce(status.FieldPlaceID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *StatusQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(status.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = status.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StatusGroupBy is the group-by builder for Status entities.
type StatusGroupBy struct {
	selector
	build *StatusQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *StatusGroupBy) Aggregate(fns ...AggregateFunc) *StatusGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *StatusGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StatusQuery, *StatusGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *StatusGroupBy) sqlScan(ctx context.Context, root *StatusQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StatusSelect is the builder for selecting fields of Status entities.
type StatusSelect struct {
	*StatusQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *StatusSelect) Aggregate(fns ...AggregateFunc) *StatusSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *StatusSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StatusQuery, *StatusSelect](ctx, _s.StatusQuery, _s, _s.inters, v)
}

func (_s *StatusSelect) sqlScan(ctx context.Context, root *StatusQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
