// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/hashtag"
	"glintfed/ent/predicate"
	"glintfed/ent/profile"
	"glintfed/ent/status"
	"glintfed/ent/statushashtag"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StatusHashtagUpdate is the builder for updating StatusHashtag entities.
type StatusHashtagUpdate struct {
	config
	hooks    []Hook
	mutation *StatusHashtagMutation
}

// Where appends a list predicates to the StatusHashtagUpdate builder.
func (_u *StatusHashtagUpdate) Where(ps ...predicate.StatusHashtag) *StatusHashtagUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatusID sets the "status_id" field.
func (_u *StatusHashtagUpdate) SetStatusID(v uint64) *StatusHashtagUpdate {
	_u.mutation.SetStatusID(v)
	return _u
}

// SetNillableStatusID sets the "status_id" field if the given value is not nil.
func (_u *StatusHashtagUpdate) SetNillableStatusID(v *uint64) *StatusHashtagUpdate {
	if v != nil {
		_u.SetStatusID(*v)
	}
	return _u
}

// SetHashtagID sets the "hashtag_id" field.
func (_u *StatusHashtagUpdate) SetHashtagID(v uint64) *StatusHashtagUpdate {
	_u.mutation.SetHashtagID(v)
	return _u
}

// SetNillableHashtagID sets the "hashtag_id" field if the given value is not nil.
func (_u *StatusHashtagUpdate) SetNillableHashtagID(v *uint64) *StatusHashtagUpdate {
	if v != nil {
		_u.SetHashtagID(*v)
	}
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *StatusHashtagUpdate) SetProfileID(v uint64) *StatusHashtagUpdate {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *StatusHashtagUpdate) SetNillableProfileID(v *uint64) *StatusHashtagUpdate {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// ClearProfileID clears the value of the "profile_id" field.
func (_u *StatusHashtagUpdate) ClearProfileID() *StatusHashtagUpdate {
	_u.mutation.ClearProfileID()
	return _u
}

// SetStatusVisibility sets the "status_visibility" field.
func (_u *StatusHashtagUpdate) SetStatusVisibility(v string) *StatusHashtagUpdate {
	_u.mutation.SetStatusVisibility(v)
	return _u
}

// SetNillableStatusVisibility sets the "status_visibility" field if the given value is not nil.
func (_u *StatusHashtagUpdate) SetNillableStatusVisibility(v *string) *StatusHashtagUpdate {
	if v != nil {
		_u.SetStatusVisibility(*v)
	}
	return _u
}

// ClearStatusVisibility clears the value of the "status_visibility" field.
func (_u *StatusHashtagUpdate) ClearStatusVisibility() *StatusHashtagUpdate {
	_u.mutation.ClearStatusVisibility()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StatusHashtagUpdate) SetCreatedAt(v time.Time) *StatusHashtagUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StatusHashtagUpdate) SetNillableCreatedAt(v *time.Time) *StatusHashtagUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *StatusHashtagUpdate) ClearCreatedAt() *StatusHashtagUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusHashtagUpdate) SetUpdatedAt(v time.Time) *StatusHashtagUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StatusHashtagUpdate) SetNillableUpdatedAt(v *time.Time) *StatusHashtagUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *StatusHashtagUpdate) ClearUpdatedAt() *StatusHashtagUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetStatus sets the "status" edge to the Status entity.
func (_u *StatusHashtagUpdate) SetStatus(v *Status) *StatusHashtagUpdate {
	return _u.SetStatusID(v.ID)
}

// SetHashtag sets the "hashtag" edge to the Hashtag entity.
func (_u *StatusHashtagUpdate) SetHashtag(v *Hashtag) *StatusHashtagUpdate {
	return _u.SetHashtagID(v.ID)
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_u *StatusHashtagUpdate) SetProfile(v *Profile) *StatusHashtagUpdate {
	return _u.SetProfileID(v.ID)
}

// Mutation returns the StatusHashtagMutation object of the builder.
func (_u *StatusHashtagUpdate) Mutation() *StatusHashtagMutation {
	return _u.mutation
}

// ClearStatus clears the "status" edge to the Status entity.
func (_u *StatusHashtagUpdate) ClearStatus() *StatusHashtagUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// ClearHashtag clears the "hashtag" edge to the Hashtag entity.
func (_u *StatusHashtagUpdate) ClearHashtag() *StatusHashtagUpdate {
	_u.mutation.ClearHashtag()
	return _u
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (_u *StatusHashtagUpdate) ClearProfile() *StatusHashtagUpdate {
	_u.mutation.ClearProfile()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *StatusHashtagUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusHashtagUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *StatusHashtagUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusHashtagUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusHashtagUpdate) check() error {
	if _u.mutation.StatusCleared() && len(_u.mutation.StatusIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StatusHashtag.status"`)
	}
	if _u.mutation.HashtagCleared() && len(_u.mutation.HashtagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StatusHashtag.hashtag"`)
	}
	return nil
}

func (_u *StatusHashtagUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(statushashtag.Table, statushashtag.Columns, sqlgraph.NewFieldSpec(statushashtag.FieldID, field.TypeUint64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StatusVisibility(); ok {
		_spec.SetField(statushashtag.FieldStatusVisibility, field.TypeString, value)
	}
	if _u.mutation.StatusVisibilityCleared() {
		_spec.ClearField(statushashtag.FieldStatusVisibility, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(statushashtag.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(statushashtag.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statushashtag.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(statushashtag.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.StatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.StatusTable,
			Columns: []string{statushashtag.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.StatusTable,
			Columns: []string{statushashtag.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HashtagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.HashtagTable,
			Columns: []string{statushashtag.HashtagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hashtag.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HashtagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.HashtagTable,
			Columns: []string{statushashtag.HashtagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hashtag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.ProfileTable,
			Columns: []string{statushashtag.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.ProfileTable,
			Columns: []string{statushashtag.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statushashtag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// StatusHashtagUpdateOne is the builder for updating a single StatusHashtag entity.
type StatusHashtagUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *StatusHashtagMutation
}

// SetStatusID sets the "status_id" field.
func (_u *StatusHashtagUpdateOne) SetStatusID(v uint64) *StatusHashtagUpdateOne {
	_u.mutation.SetStatusID(v)
	return _u
}

// SetNillableStatusID sets the "status_id" field if the given value is not nil.
func (_u *StatusHashtagUpdateOne) SetNillableStatusID(v *uint64) *StatusHashtagUpdateOne {
	if v != nil {
		_u.SetStatusID(*v)
	}
	return _u
}

// SetHashtagID sets the "hashtag_id" field.
func (_u *StatusHashtagUpdateOne) SetHashtagID(v uint64) *StatusHashtagUpdateOne {
	_u.mutation.SetHashtagID(v)
	return _u
}

// SetNillableHashtagID sets the "hashtag_id" field if the given value is not nil.
func (_u *StatusHashtagUpdateOne) SetNillableHashtagID(v *uint64) *StatusHashtagUpdateOne {
	if v != nil {
		_u.SetHashtagID(*v)
	}
	return _u
}

// SetProfileID sets the "profile_id" field.
func (_u *StatusHashtagUpdateOne) SetProfileID(v uint64) *StatusHashtagUpdateOne {
	_u.mutation.SetProfileID(v)
	return _u
}

// SetNillableProfileID sets the "profile_id" field if the given value is not nil.
func (_u *StatusHashtagUpdateOne) SetNillableProfileID(v *uint64) *StatusHashtagUpdateOne {
	if v != nil {
		_u.SetProfileID(*v)
	}
	return _u
}

// ClearProfileID clears the value of the "profile_id" field.
func (_u *StatusHashtagUpdateOne) ClearProfileID() *StatusHashtagUpdateOne {
	_u.mutation.ClearProfileID()
	return _u
}

// SetStatusVisibility sets the "status_visibility" field.
func (_u *StatusHashtagUpdateOne) SetStatusVisibility(v string) *StatusHashtagUpdateOne {
	_u.mutation.SetStatusVisibility(v)
	return _u
}

// SetNillableStatusVisibility sets the "status_visibility" field if the given value is not nil.
func (_u *StatusHashtagUpdateOne) SetNillableStatusVisibility(v *string) *StatusHashtagUpdateOne {
	if v != nil {
		_u.SetStatusVisibility(*v)
	}
	return _u
}

// ClearStatusVisibility clears the value of the "status_visibility" field.
func (_u *StatusHashtagUpdateOne) ClearStatusVisibility() *StatusHashtagUpdateOne {
	_u.mutation.ClearStatusVisibility()
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *StatusHashtagUpdateOne) SetCreatedAt(v time.Time) *StatusHashtagUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *StatusHashtagUpdateOne) SetNillableCreatedAt(v *time.Time) *StatusHashtagUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *StatusHashtagUpdateOne) ClearCreatedAt() *StatusHashtagUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *StatusHashtagUpdateOne) SetUpdatedAt(v time.Time) *StatusHashtagUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *StatusHashtagUpdateOne) SetNillableUpdatedAt(v *time.Time) *StatusHashtagUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *StatusHashtagUpdateOne) ClearUpdatedAt() *StatusHashtagUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetStatus sets the "status" edge to the Status entity.
func (_u *StatusHashtagUpdateOne) SetStatus(v *Status) *StatusHashtagUpdateOne {
	return _u.SetStatusID(v.ID)
}

// SetHashtag sets the "hashtag" edge to the Hashtag entity.
func (_u *StatusHashtagUpdateOne) SetHashtag(v *Hashtag) *StatusHashtagUpdateOne {
	return _u.SetHashtagID(v.ID)
}

// SetProfile sets the "profile" edge to the Profile entity.
func (_u *StatusHashtagUpdateOne) SetProfile(v *Profile) *StatusHashtagUpdateOne {
	return _u.SetProfileID(v.ID)
}

// Mutation returns the StatusHashtagMutation object of the builder.
func (_u *StatusHashtagUpdateOne) Mutation() *StatusHashtagMutation {
	return _u.mutation
}

// ClearStatus clears the "status" edge to the Status entity.
func (_u *StatusHashtagUpdateOne) ClearStatus() *StatusHashtagUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// ClearHashtag clears the "hashtag" edge to the Hashtag entity.
func (_u *StatusHashtagUpdateOne) ClearHashtag() *StatusHashtagUpdateOne {
	_u.mutation.ClearHashtag()
	return _u
}

// ClearProfile clears the "profile" edge to the Profile entity.
func (_u *StatusHashtagUpdateOne) ClearProfile() *StatusHashtagUpdateOne {
	_u.mutation.ClearProfile()
	return _u
}

// Where appends a list predicates to the StatusHashtagUpdate builder.
func (_u *StatusHashtagUpdateOne) Where(ps ...predicate.StatusHashtag) *StatusHashtagUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *StatusHashtagUpdateOne) Select(field string, fields ...string) *StatusHashtagUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated StatusHashtag entity.
func (_u *StatusHashtagUpdateOne) Save(ctx context.Context) (*StatusHashtag, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *StatusHashtagUpdateOne) SaveX(ctx context.Context) *StatusHashtag {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *StatusHashtagUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *StatusHashtagUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *StatusHashtagUpdateOne) check() error {
	if _u.mutation.StatusCleared() && len(_u.mutation.StatusIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StatusHashtag.status"`)
	}
	if _u.mutation.HashtagCleared() && len(_u.mutation.HashtagIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "StatusHashtag.hashtag"`)
	}
	return nil
}

func (_u *StatusHashtagUpdateOne) sqlSave(ctx context.Context) (_node *StatusHashtag, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(statushashtag.Table, statushashtag.Columns, sqlgraph.NewFieldSpec(statushashtag.FieldID, field.TypeUint64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "StatusHashtag.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statushashtag.FieldID)
		for _, f := range fields {
			if !statushashtag.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != statushashtag.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.StatusVisibility(); ok {
		_spec.SetField(statushashtag.FieldStatusVisibility, field.TypeString, value)
	}
	if _u.mutation.StatusVisibilityCleared() {
		_spec.ClearField(statushashtag.FieldStatusVisibility, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(statushashtag.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(statushashtag.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(statushashtag.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(statushashtag.FieldUpdatedAt, field.TypeTime)
	}
	if _u.mutation.StatusCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.StatusTable,
			Columns: []string{statushashtag.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.StatusIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.StatusTable,
			Columns: []string{statushashtag.StatusColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(status.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.HashtagCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.HashtagTable,
			Columns: []string{statushashtag.HashtagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hashtag.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.HashtagIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.HashtagTable,
			Columns: []string{statushashtag.HashtagColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(hashtag.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ProfileCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.ProfileTable,
			Columns: []string{statushashtag.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProfileIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   statushashtag.ProfileTable,
			Columns: []string{statushashtag.ProfileColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(profile.FieldID, field.TypeUint64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &StatusHashtag{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{statushashtag.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
