// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"glintfed/ent/statusedit"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// StatusEdit is the model entity for the StatusEdit schema.
type StatusEdit struct {
	config `json:"-"`
	// ID of the ent.
	ID uint64 `json:"id,omitempty"`
	// StatusID holds the value of the "status_id" field.
	StatusID uint64 `json:"status_id,omitempty"`
	// ProfileID holds the value of the "profile_id" field.
	ProfileID uint64 `json:"profile_id,omitempty"`
	// Caption holds the value of the "caption" field.
	Caption *string `json:"caption,omitempty"`
	// SpoilerText holds the value of the "spoiler_text" field.
	SpoilerText *string `json:"spoiler_text,omitempty"`
	// OrderedMediaAttachmentIds holds the value of the "ordered_media_attachment_ids" field.
	OrderedMediaAttachmentIds *string `json:"ordered_media_attachment_ids,omitempty"`
	// MediaDescriptions holds the value of the "media_descriptions" field.
	MediaDescriptions *string `json:"media_descriptions,omitempty"`
	// PollOptions holds the value of the "poll_options" field.
	PollOptions *string `json:"poll_options,omitempty"`
	// IsNsfw holds the value of the "is_nsfw" field.
	IsNsfw *bool `json:"is_nsfw,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt *time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    *time.Time `json:"updated_at,omitempty"`
	status_edits *uint64
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*StatusEdit) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case statusedit.FieldIsNsfw:
			values[i] = new(sql.NullBool)
		case statusedit.FieldID, statusedit.FieldStatusID, statusedit.FieldProfileID:
			values[i] = new(sql.NullInt64)
		case statusedit.FieldCaption, statusedit.FieldSpoilerText, statusedit.FieldOrderedMediaAttachmentIds, statusedit.FieldMediaDescriptions, statusedit.FieldPollOptions:
			values[i] = new(sql.NullString)
		case statusedit.FieldCreatedAt, statusedit.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case statusedit.ForeignKeys[0]: // status_edits
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the StatusEdit fields.
func (_m *StatusEdit) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case statusedit.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = uint64(value.Int64)
		case statusedit.FieldStatusID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field status_id", values[i])
			} else if value.Valid {
				_m.StatusID = uint64(value.Int64)
			}
		case statusedit.FieldProfileID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field profile_id", values[i])
			} else if value.Valid {
				_m.ProfileID = uint64(value.Int64)
			}
		case statusedit.FieldCaption:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field caption", values[i])
			} else if value.Valid {
				_m.Caption = new(string)
				*_m.Caption = value.String
			}
		case statusedit.FieldSpoilerText:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field spoiler_text", values[i])
			} else if value.Valid {
				_m.SpoilerText = new(string)
				*_m.SpoilerText = value.String
			}
		case statusedit.FieldOrderedMediaAttachmentIds:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ordered_media_attachment_ids", values[i])
			} else if value.Valid {
				_m.OrderedMediaAttachmentIds = new(string)
				*_m.OrderedMediaAttachmentIds = value.String
			}
		case statusedit.FieldMediaDescriptions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field media_descriptions", values[i])
			} else if value.Valid {
				_m.MediaDescriptions = new(string)
				*_m.MediaDescriptions = value.String
			}
		case statusedit.FieldPollOptions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field poll_options", values[i])
			} else if value.Valid {
				_m.PollOptions = new(string)
				*_m.PollOptions = value.String
			}
		case statusedit.FieldIsNsfw:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_nsfw", values[i])
			} else if value.Valid {
				_m.IsNsfw = new(bool)
				*_m.IsNsfw = value.Bool
			}
		case statusedit.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = new(time.Time)
				*_m.CreatedAt = value.Time
			}
		case statusedit.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = new(time.Time)
				*_m.UpdatedAt = value.Time
			}
		case statusedit.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field status_edits", value)
			} else if value.Valid {
				_m.status_edits = new(uint64)
				*_m.status_edits = uint64(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the StatusEdit.
// This includes values selected through modifiers, order, etc.
func (_m *StatusEdit) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this StatusEdit.
// Note that you need to call StatusEdit.Unwrap() before calling this method if this StatusEdit
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *StatusEdit) Update() *StatusEditUpdateOne {
	return NewStatusEditClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the StatusEdit entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *StatusEdit) Unwrap() *StatusEdit {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: StatusEdit is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *StatusEdit) String() string {
	var builder strings.Builder
	builder.WriteString("StatusEdit(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.StatusID))
	builder.WriteString(", ")
	builder.WriteString("profile_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProfileID))
	builder.WriteString(", ")
	if v := _m.Caption; v != nil {
		builder.WriteString("caption=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SpoilerText; v != nil {
		builder.WriteString("spoiler_text=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OrderedMediaAttachmentIds; v != nil {
		builder.WriteString("ordered_media_attachment_ids=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.MediaDescriptions; v != nil {
		builder.WriteString("media_descriptions=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.PollOptions; v != nil {
		builder.WriteString("poll_options=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.IsNsfw; v != nil {
		builder.WriteString("is_nsfw=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CreatedAt; v != nil {
		builder.WriteString("created_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.UpdatedAt; v != nil {
		builder.WriteString("updated_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// StatusEdits is a parsable slice of StatusEdit.
type StatusEdits []*StatusEdit
