// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/predicate"
	"glintfed/ent/telescopemonitoring"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TelescopeMonitoringUpdate is the builder for updating TelescopeMonitoring entities.
type TelescopeMonitoringUpdate struct {
	config
	hooks    []Hook
	mutation *TelescopeMonitoringMutation
}

// Where appends a list predicates to the TelescopeMonitoringUpdate builder.
func (_u *TelescopeMonitoringUpdate) Where(ps ...predicate.TelescopeMonitoring) *TelescopeMonitoringUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTag sets the "tag" field.
func (_u *TelescopeMonitoringUpdate) SetTag(v string) *TelescopeMonitoringUpdate {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *TelescopeMonitoringUpdate) SetNillableTag(v *string) *TelescopeMonitoringUpdate {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// Mutation returns the TelescopeMonitoringMutation object of the builder.
func (_u *TelescopeMonitoringUpdate) Mutation() *TelescopeMonitoringMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TelescopeMonitoringUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TelescopeMonitoringUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TelescopeMonitoringUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TelescopeMonitoringUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TelescopeMonitoringUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(telescopemonitoring.Table, telescopemonitoring.Columns, sqlgraph.NewFieldSpec(telescopemonitoring.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(telescopemonitoring.FieldTag, field.TypeString, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{telescopemonitoring.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TelescopeMonitoringUpdateOne is the builder for updating a single TelescopeMonitoring entity.
type TelescopeMonitoringUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TelescopeMonitoringMutation
}

// SetTag sets the "tag" field.
func (_u *TelescopeMonitoringUpdateOne) SetTag(v string) *TelescopeMonitoringUpdateOne {
	_u.mutation.SetTag(v)
	return _u
}

// SetNillableTag sets the "tag" field if the given value is not nil.
func (_u *TelescopeMonitoringUpdateOne) SetNillableTag(v *string) *TelescopeMonitoringUpdateOne {
	if v != nil {
		_u.SetTag(*v)
	}
	return _u
}

// Mutation returns the TelescopeMonitoringMutation object of the builder.
func (_u *TelescopeMonitoringUpdateOne) Mutation() *TelescopeMonitoringMutation {
	return _u.mutation
}

// Where appends a list predicates to the TelescopeMonitoringUpdate builder.
func (_u *TelescopeMonitoringUpdateOne) Where(ps ...predicate.TelescopeMonitoring) *TelescopeMonitoringUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TelescopeMonitoringUpdateOne) Select(field string, fields ...string) *TelescopeMonitoringUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TelescopeMonitoring entity.
func (_u *TelescopeMonitoringUpdateOne) Save(ctx context.Context) (*TelescopeMonitoring, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TelescopeMonitoringUpdateOne) SaveX(ctx context.Context) *TelescopeMonitoring {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TelescopeMonitoringUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TelescopeMonitoringUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *TelescopeMonitoringUpdateOne) sqlSave(ctx context.Context) (_node *TelescopeMonitoring, err error) {
	_spec := sqlgraph.NewUpdateSpec(telescopemonitoring.Table, telescopemonitoring.Columns, sqlgraph.NewFieldSpec(telescopemonitoring.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TelescopeMonitoring.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, telescopemonitoring.FieldID)
		for _, f := range fields {
			if !telescopemonitoring.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != telescopemonitoring.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tag(); ok {
		_spec.SetField(telescopemonitoring.FieldTag, field.TypeString, value)
	}
	_node = &TelescopeMonitoring{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{telescopemonitoring.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
