// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/telescopemonitoring"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TelescopeMonitoringCreate is the builder for creating a TelescopeMonitoring entity.
type TelescopeMonitoringCreate struct {
	config
	mutation *TelescopeMonitoringMutation
	hooks    []Hook
}

// SetTag sets the "tag" field.
func (_c *TelescopeMonitoringCreate) SetTag(v string) *TelescopeMonitoringCreate {
	_c.mutation.SetTag(v)
	return _c
}

// Mutation returns the TelescopeMonitoringMutation object of the builder.
func (_c *TelescopeMonitoringCreate) Mutation() *TelescopeMonitoringMutation {
	return _c.mutation
}

// Save creates the TelescopeMonitoring in the database.
func (_c *TelescopeMonitoringCreate) Save(ctx context.Context) (*TelescopeMonitoring, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TelescopeMonitoringCreate) SaveX(ctx context.Context) *TelescopeMonitoring {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TelescopeMonitoringCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TelescopeMonitoringCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TelescopeMonitoringCreate) check() error {
	if _, ok := _c.mutation.Tag(); !ok {
		return &ValidationError{Name: "tag", err: errors.New(`ent: missing required field "TelescopeMonitoring.tag"`)}
	}
	return nil
}

func (_c *TelescopeMonitoringCreate) sqlSave(ctx context.Context) (*TelescopeMonitoring, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TelescopeMonitoringCreate) createSpec() (*TelescopeMonitoring, *sqlgraph.CreateSpec) {
	var (
		_node = &TelescopeMonitoring{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(telescopemonitoring.Table, sqlgraph.NewFieldSpec(telescopemonitoring.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Tag(); ok {
		_spec.SetField(telescopemonitoring.FieldTag, field.TypeString, value)
		_node.Tag = value
	}
	return _node, _spec
}

// TelescopeMonitoringCreateBulk is the builder for creating many TelescopeMonitoring entities in bulk.
type TelescopeMonitoringCreateBulk struct {
	config
	err      error
	builders []*TelescopeMonitoringCreate
}

// Save creates the TelescopeMonitoring entities in the database.
func (_c *TelescopeMonitoringCreateBulk) Save(ctx context.Context) ([]*TelescopeMonitoring, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TelescopeMonitoring, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TelescopeMonitoringMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TelescopeMonitoringCreateBulk) SaveX(ctx context.Context) []*TelescopeMonitoring {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TelescopeMonitoringCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TelescopeMonitoringCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
