// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"glintfed/ent/predicate"
	"glintfed/ent/websocketsstatisticsentry"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WebsocketsStatisticsEntryUpdate is the builder for updating WebsocketsStatisticsEntry entities.
type WebsocketsStatisticsEntryUpdate struct {
	config
	hooks    []Hook
	mutation *WebsocketsStatisticsEntryMutation
}

// Where appends a list predicates to the WebsocketsStatisticsEntryUpdate builder.
func (_u *WebsocketsStatisticsEntryUpdate) Where(ps ...predicate.WebsocketsStatisticsEntry) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *WebsocketsStatisticsEntryUpdate) SetAppID(v string) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdate) SetNillableAppID(v *string) *WebsocketsStatisticsEntryUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetPeakConnectionCount sets the "peak_connection_count" field.
func (_u *WebsocketsStatisticsEntryUpdate) SetPeakConnectionCount(v int) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.ResetPeakConnectionCount()
	_u.mutation.SetPeakConnectionCount(v)
	return _u
}

// SetNillablePeakConnectionCount sets the "peak_connection_count" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdate) SetNillablePeakConnectionCount(v *int) *WebsocketsStatisticsEntryUpdate {
	if v != nil {
		_u.SetPeakConnectionCount(*v)
	}
	return _u
}

// AddPeakConnectionCount adds value to the "peak_connection_count" field.
func (_u *WebsocketsStatisticsEntryUpdate) AddPeakConnectionCount(v int) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.AddPeakConnectionCount(v)
	return _u
}

// SetWebsocketMessageCount sets the "websocket_message_count" field.
func (_u *WebsocketsStatisticsEntryUpdate) SetWebsocketMessageCount(v int) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.ResetWebsocketMessageCount()
	_u.mutation.SetWebsocketMessageCount(v)
	return _u
}

// SetNillableWebsocketMessageCount sets the "websocket_message_count" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdate) SetNillableWebsocketMessageCount(v *int) *WebsocketsStatisticsEntryUpdate {
	if v != nil {
		_u.SetWebsocketMessageCount(*v)
	}
	return _u
}

// AddWebsocketMessageCount adds value to the "websocket_message_count" field.
func (_u *WebsocketsStatisticsEntryUpdate) AddWebsocketMessageCount(v int) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.AddWebsocketMessageCount(v)
	return _u
}

// SetAPIMessageCount sets the "api_message_count" field.
func (_u *WebsocketsStatisticsEntryUpdate) SetAPIMessageCount(v int) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.ResetAPIMessageCount()
	_u.mutation.SetAPIMessageCount(v)
	return _u
}

// SetNillableAPIMessageCount sets the "api_message_count" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdate) SetNillableAPIMessageCount(v *int) *WebsocketsStatisticsEntryUpdate {
	if v != nil {
		_u.SetAPIMessageCount(*v)
	}
	return _u
}

// AddAPIMessageCount adds value to the "api_message_count" field.
func (_u *WebsocketsStatisticsEntryUpdate) AddAPIMessageCount(v int) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.AddAPIMessageCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WebsocketsStatisticsEntryUpdate) SetCreatedAt(v time.Time) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdate) SetNillableCreatedAt(v *time.Time) *WebsocketsStatisticsEntryUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *WebsocketsStatisticsEntryUpdate) ClearCreatedAt() *WebsocketsStatisticsEntryUpdate {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebsocketsStatisticsEntryUpdate) SetUpdatedAt(v time.Time) *WebsocketsStatisticsEntryUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdate) SetNillableUpdatedAt(v *time.Time) *WebsocketsStatisticsEntryUpdate {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *WebsocketsStatisticsEntryUpdate) ClearUpdatedAt() *WebsocketsStatisticsEntryUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the WebsocketsStatisticsEntryMutation object of the builder.
func (_u *WebsocketsStatisticsEntryUpdate) Mutation() *WebsocketsStatisticsEntryMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WebsocketsStatisticsEntryUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebsocketsStatisticsEntryUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WebsocketsStatisticsEntryUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebsocketsStatisticsEntryUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WebsocketsStatisticsEntryUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(websocketsstatisticsentry.Table, websocketsstatisticsentry.Columns, sqlgraph.NewFieldSpec(websocketsstatisticsentry.FieldID, field.TypeUint))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeakConnectionCount(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldPeakConnectionCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakConnectionCount(); ok {
		_spec.AddField(websocketsstatisticsentry.FieldPeakConnectionCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WebsocketMessageCount(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldWebsocketMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWebsocketMessageCount(); ok {
		_spec.AddField(websocketsstatisticsentry.FieldWebsocketMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIMessageCount(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldAPIMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIMessageCount(); ok {
		_spec.AddField(websocketsstatisticsentry.FieldAPIMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(websocketsstatisticsentry.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(websocketsstatisticsentry.FieldUpdatedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{websocketsstatisticsentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WebsocketsStatisticsEntryUpdateOne is the builder for updating a single WebsocketsStatisticsEntry entity.
type WebsocketsStatisticsEntryUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WebsocketsStatisticsEntryMutation
}

// SetAppID sets the "app_id" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetAppID(v string) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetNillableAppID(v *string) *WebsocketsStatisticsEntryUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetPeakConnectionCount sets the "peak_connection_count" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetPeakConnectionCount(v int) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.ResetPeakConnectionCount()
	_u.mutation.SetPeakConnectionCount(v)
	return _u
}

// SetNillablePeakConnectionCount sets the "peak_connection_count" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetNillablePeakConnectionCount(v *int) *WebsocketsStatisticsEntryUpdateOne {
	if v != nil {
		_u.SetPeakConnectionCount(*v)
	}
	return _u
}

// AddPeakConnectionCount adds value to the "peak_connection_count" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) AddPeakConnectionCount(v int) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.AddPeakConnectionCount(v)
	return _u
}

// SetWebsocketMessageCount sets the "websocket_message_count" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetWebsocketMessageCount(v int) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.ResetWebsocketMessageCount()
	_u.mutation.SetWebsocketMessageCount(v)
	return _u
}

// SetNillableWebsocketMessageCount sets the "websocket_message_count" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetNillableWebsocketMessageCount(v *int) *WebsocketsStatisticsEntryUpdateOne {
	if v != nil {
		_u.SetWebsocketMessageCount(*v)
	}
	return _u
}

// AddWebsocketMessageCount adds value to the "websocket_message_count" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) AddWebsocketMessageCount(v int) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.AddWebsocketMessageCount(v)
	return _u
}

// SetAPIMessageCount sets the "api_message_count" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetAPIMessageCount(v int) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.ResetAPIMessageCount()
	_u.mutation.SetAPIMessageCount(v)
	return _u
}

// SetNillableAPIMessageCount sets the "api_message_count" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetNillableAPIMessageCount(v *int) *WebsocketsStatisticsEntryUpdateOne {
	if v != nil {
		_u.SetAPIMessageCount(*v)
	}
	return _u
}

// AddAPIMessageCount adds value to the "api_message_count" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) AddAPIMessageCount(v int) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.AddAPIMessageCount(v)
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetCreatedAt(v time.Time) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetNillableCreatedAt(v *time.Time) *WebsocketsStatisticsEntryUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) ClearCreatedAt() *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.ClearCreatedAt()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetUpdatedAt(v time.Time) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_u *WebsocketsStatisticsEntryUpdateOne) SetNillableUpdatedAt(v *time.Time) *WebsocketsStatisticsEntryUpdateOne {
	if v != nil {
		_u.SetUpdatedAt(*v)
	}
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *WebsocketsStatisticsEntryUpdateOne) ClearUpdatedAt() *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// Mutation returns the WebsocketsStatisticsEntryMutation object of the builder.
func (_u *WebsocketsStatisticsEntryUpdateOne) Mutation() *WebsocketsStatisticsEntryMutation {
	return _u.mutation
}

// Where appends a list predicates to the WebsocketsStatisticsEntryUpdate builder.
func (_u *WebsocketsStatisticsEntryUpdateOne) Where(ps ...predicate.WebsocketsStatisticsEntry) *WebsocketsStatisticsEntryUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WebsocketsStatisticsEntryUpdateOne) Select(field string, fields ...string) *WebsocketsStatisticsEntryUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated WebsocketsStatisticsEntry entity.
func (_u *WebsocketsStatisticsEntryUpdateOne) Save(ctx context.Context) (*WebsocketsStatisticsEntry, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WebsocketsStatisticsEntryUpdateOne) SaveX(ctx context.Context) *WebsocketsStatisticsEntry {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WebsocketsStatisticsEntryUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WebsocketsStatisticsEntryUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WebsocketsStatisticsEntryUpdateOne) sqlSave(ctx context.Context) (_node *WebsocketsStatisticsEntry, err error) {
	_spec := sqlgraph.NewUpdateSpec(websocketsstatisticsentry.Table, websocketsstatisticsentry.Columns, sqlgraph.NewFieldSpec(websocketsstatisticsentry.FieldID, field.TypeUint))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "WebsocketsStatisticsEntry.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, websocketsstatisticsentry.FieldID)
		for _, f := range fields {
			if !websocketsstatisticsentry.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != websocketsstatisticsentry.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.PeakConnectionCount(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldPeakConnectionCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPeakConnectionCount(); ok {
		_spec.AddField(websocketsstatisticsentry.FieldPeakConnectionCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.WebsocketMessageCount(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldWebsocketMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedWebsocketMessageCount(); ok {
		_spec.AddField(websocketsstatisticsentry.FieldWebsocketMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.APIMessageCount(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldAPIMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAPIMessageCount(); ok {
		_spec.AddField(websocketsstatisticsentry.FieldAPIMessageCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(websocketsstatisticsentry.FieldCreatedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(websocketsstatisticsentry.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(websocketsstatisticsentry.FieldUpdatedAt, field.TypeTime)
	}
	_node = &WebsocketsStatisticsEntry{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{websocketsstatisticsentry.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
