// Code generated by ent, DO NOT EDIT.

package report

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the report type in the database.
	Label = "report"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProfileID holds the string denoting the profile_id field in the database.
	FieldProfileID = "profile_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldObjectID holds the string denoting the object_id field in the database.
	FieldObjectID = "object_id"
	// FieldObjectType holds the string denoting the object_type field in the database.
	FieldObjectType = "object_type"
	// FieldReportedProfileID holds the string denoting the reported_profile_id field in the database.
	FieldReportedProfileID = "reported_profile_id"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldMessage holds the string denoting the message field in the database.
	FieldMessage = "message"
	// FieldAdminSeen holds the string denoting the admin_seen field in the database.
	FieldAdminSeen = "admin_seen"
	// FieldNotInterested holds the string denoting the not_interested field in the database.
	FieldNotInterested = "not_interested"
	// FieldSpam holds the string denoting the spam field in the database.
	FieldSpam = "spam"
	// FieldNsfw holds the string denoting the nsfw field in the database.
	FieldNsfw = "nsfw"
	// FieldAbusive holds the string denoting the abusive field in the database.
	FieldAbusive = "abusive"
	// FieldMeta holds the string denoting the meta field in the database.
	FieldMeta = "meta"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeReporter holds the string denoting the reporter edge name in mutations.
	EdgeReporter = "reporter"
	// EdgeStatus holds the string denoting the status edge name in mutations.
	EdgeStatus = "status"
	// EdgeReportedUser holds the string denoting the reporteduser edge name in mutations.
	EdgeReportedUser = "reportedUser"
	// Table holds the table name of the report in the database.
	Table = "reports"
	// ReporterTable is the table that holds the reporter relation/edge.
	ReporterTable = "reports"
	// ReporterInverseTable is the table name for the Profile entity.
	// It exists in this package in order to avoid circular dependency with the "profile" package.
	ReporterInverseTable = "profiles"
	// ReporterColumn is the table column denoting the reporter relation/edge.
	ReporterColumn = "profile_id"
	// StatusTable is the table that holds the status relation/edge.
	StatusTable = "reports"
	// StatusInverseTable is the table name for the Status entity.
	// It exists in this package in order to avoid circular dependency with the "status" package.
	StatusInverseTable = "statuses"
	// StatusColumn is the table column denoting the status relation/edge.
	StatusColumn = "object_id"
	// ReportedUserTable is the table that holds the reportedUser relation/edge.
	ReportedUserTable = "reports"
	// ReportedUserInverseTable is the table name for the Profile entity.
	// It exists in this package in order to avoid circular dependency with the "profile" package.
	ReportedUserInverseTable = "profiles"
	// ReportedUserColumn is the table column denoting the reportedUser relation/edge.
	ReportedUserColumn = "reported_profile_id"
)

// Columns holds all SQL columns for report fields.
var Columns = []string{
	FieldID,
	FieldProfileID,
	FieldUserID,
	FieldObjectID,
	FieldObjectType,
	FieldReportedProfileID,
	FieldType,
	FieldMessage,
	FieldAdminSeen,
	FieldNotInterested,
	FieldSpam,
	FieldNsfw,
	FieldAbusive,
	FieldMeta,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "reports"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"profile_reported",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Report queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByProfileID orders the results by the profile_id field.
func ByProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProfileID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByObjectID orders the results by the object_id field.
func ByObjectID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectID, opts...).ToFunc()
}

// ByObjectType orders the results by the object_type field.
func ByObjectType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldObjectType, opts...).ToFunc()
}

// ByReportedProfileID orders the results by the reported_profile_id field.
func ByReportedProfileID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReportedProfileID, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByMessage orders the results by the message field.
func ByMessage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMessage, opts...).ToFunc()
}

// ByAdminSeen orders the results by the admin_seen field.
func ByAdminSeen(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdminSeen, opts...).ToFunc()
}

// ByNotInterested orders the results by the not_interested field.
func ByNotInterested(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNotInterested, opts...).ToFunc()
}

// BySpam orders the results by the spam field.
func BySpam(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSpam, opts...).ToFunc()
}

// ByNsfw orders the results by the nsfw field.
func ByNsfw(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNsfw, opts...).ToFunc()
}

// ByAbusive orders the results by the abusive field.
func ByAbusive(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAbusive, opts...).ToFunc()
}

// ByMeta orders the results by the meta field.
func ByMeta(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeta, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByReporterField orders the results by reporter field.
func ByReporterField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReporterStep(), sql.OrderByField(field, opts...))
	}
}

// ByStatusField orders the results by status field.
func ByStatusField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newStatusStep(), sql.OrderByField(field, opts...))
	}
}

// ByReportedUserField orders the results by reportedUser field.
func ByReportedUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReportedUserStep(), sql.OrderByField(field, opts...))
	}
}
func newReporterStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReporterInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ReporterTable, ReporterColumn),
	)
}
func newStatusStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(StatusInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, StatusTable, StatusColumn),
	)
}
func newReportedUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReportedUserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ReportedUserTable, ReportedUserColumn),
	)
}
