// Code generated by ent, DO NOT EDIT.

package telescopeentry

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the telescopeentry type in the database.
	Label = "telescope_entry"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSequence holds the string denoting the sequence field in the database.
	FieldSequence = "sequence"
	// FieldUUID holds the string denoting the uuid field in the database.
	FieldUUID = "uuid"
	// FieldBatchID holds the string denoting the batch_id field in the database.
	FieldBatchID = "batch_id"
	// FieldFamilyHash holds the string denoting the family_hash field in the database.
	FieldFamilyHash = "family_hash"
	// FieldShouldDisplayOnIndex holds the string denoting the should_display_on_index field in the database.
	FieldShouldDisplayOnIndex = "should_display_on_index"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the telescopeentry in the database.
	Table = "telescope_entries"
)

// Columns holds all SQL columns for telescopeentry fields.
var Columns = []string{
	FieldID,
	FieldSequence,
	FieldUUID,
	FieldBatchID,
	FieldFamilyHash,
	FieldShouldDisplayOnIndex,
	FieldType,
	FieldContent,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the TelescopeEntry queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySequence orders the results by the sequence field.
func BySequence(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSequence, opts...).ToFunc()
}

// ByUUID orders the results by the uuid field.
func ByUUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUUID, opts...).ToFunc()
}

// ByBatchID orders the results by the batch_id field.
func ByBatchID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBatchID, opts...).ToFunc()
}

// ByFamilyHash orders the results by the family_hash field.
func ByFamilyHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFamilyHash, opts...).ToFunc()
}

// ByShouldDisplayOnIndex orders the results by the should_display_on_index field.
func ByShouldDisplayOnIndex(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShouldDisplayOnIndex, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
