// Code generated by ent, DO NOT EDIT.

package userappsettings

import (
	"glintfed/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldUserID, v))
}

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldProfileID, v))
}

// Common applies equality check predicate on the "common" field. It's identical to CommonEQ.
func Common(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldCommon, v))
}

// Custom applies equality check predicate on the "custom" field. It's identical to CustomEQ.
func Custom(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldCustom, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotIn(FieldUserID, vs...))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotIn(FieldProfileID, vs...))
}

// ProfileIDGT applies the GT predicate on the "profile_id" field.
func ProfileIDGT(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGT(FieldProfileID, v))
}

// ProfileIDGTE applies the GTE predicate on the "profile_id" field.
func ProfileIDGTE(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGTE(FieldProfileID, v))
}

// ProfileIDLT applies the LT predicate on the "profile_id" field.
func ProfileIDLT(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLT(FieldProfileID, v))
}

// ProfileIDLTE applies the LTE predicate on the "profile_id" field.
func ProfileIDLTE(v uint64) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLTE(FieldProfileID, v))
}

// CommonEQ applies the EQ predicate on the "common" field.
func CommonEQ(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldCommon, v))
}

// CommonNEQ applies the NEQ predicate on the "common" field.
func CommonNEQ(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNEQ(FieldCommon, v))
}

// CommonIn applies the In predicate on the "common" field.
func CommonIn(vs ...string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIn(FieldCommon, vs...))
}

// CommonNotIn applies the NotIn predicate on the "common" field.
func CommonNotIn(vs ...string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotIn(FieldCommon, vs...))
}

// CommonGT applies the GT predicate on the "common" field.
func CommonGT(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGT(FieldCommon, v))
}

// CommonGTE applies the GTE predicate on the "common" field.
func CommonGTE(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGTE(FieldCommon, v))
}

// CommonLT applies the LT predicate on the "common" field.
func CommonLT(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLT(FieldCommon, v))
}

// CommonLTE applies the LTE predicate on the "common" field.
func CommonLTE(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLTE(FieldCommon, v))
}

// CommonContains applies the Contains predicate on the "common" field.
func CommonContains(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldContains(FieldCommon, v))
}

// CommonHasPrefix applies the HasPrefix predicate on the "common" field.
func CommonHasPrefix(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldHasPrefix(FieldCommon, v))
}

// CommonHasSuffix applies the HasSuffix predicate on the "common" field.
func CommonHasSuffix(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldHasSuffix(FieldCommon, v))
}

// CommonIsNil applies the IsNil predicate on the "common" field.
func CommonIsNil() predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIsNull(FieldCommon))
}

// CommonNotNil applies the NotNil predicate on the "common" field.
func CommonNotNil() predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotNull(FieldCommon))
}

// CommonEqualFold applies the EqualFold predicate on the "common" field.
func CommonEqualFold(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEqualFold(FieldCommon, v))
}

// CommonContainsFold applies the ContainsFold predicate on the "common" field.
func CommonContainsFold(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldContainsFold(FieldCommon, v))
}

// CustomEQ applies the EQ predicate on the "custom" field.
func CustomEQ(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldCustom, v))
}

// CustomNEQ applies the NEQ predicate on the "custom" field.
func CustomNEQ(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNEQ(FieldCustom, v))
}

// CustomIn applies the In predicate on the "custom" field.
func CustomIn(vs ...string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIn(FieldCustom, vs...))
}

// CustomNotIn applies the NotIn predicate on the "custom" field.
func CustomNotIn(vs ...string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotIn(FieldCustom, vs...))
}

// CustomGT applies the GT predicate on the "custom" field.
func CustomGT(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGT(FieldCustom, v))
}

// CustomGTE applies the GTE predicate on the "custom" field.
func CustomGTE(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGTE(FieldCustom, v))
}

// CustomLT applies the LT predicate on the "custom" field.
func CustomLT(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLT(FieldCustom, v))
}

// CustomLTE applies the LTE predicate on the "custom" field.
func CustomLTE(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLTE(FieldCustom, v))
}

// CustomContains applies the Contains predicate on the "custom" field.
func CustomContains(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldContains(FieldCustom, v))
}

// CustomHasPrefix applies the HasPrefix predicate on the "custom" field.
func CustomHasPrefix(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldHasPrefix(FieldCustom, v))
}

// CustomHasSuffix applies the HasSuffix predicate on the "custom" field.
func CustomHasSuffix(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldHasSuffix(FieldCustom, v))
}

// CustomIsNil applies the IsNil predicate on the "custom" field.
func CustomIsNil() predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIsNull(FieldCustom))
}

// CustomNotNil applies the NotNil predicate on the "custom" field.
func CustomNotNil() predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotNull(FieldCustom))
}

// CustomEqualFold applies the EqualFold predicate on the "custom" field.
func CustomEqualFold(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEqualFold(FieldCustom, v))
}

// CustomContainsFold applies the ContainsFold predicate on the "custom" field.
func CustomContainsFold(v string) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldContainsFold(FieldCustom, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.FieldNotNull(FieldUpdatedAt))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.UserAppSettings {
	return predicate.UserAppSettings(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.UserAppSettings {
	return predicate.UserAppSettings(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserAppSettings) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserAppSettings) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserAppSettings) predicate.UserAppSettings {
	return predicate.UserAppSettings(sql.NotPredicates(p))
}
